# Load Data + Import

isbn yg kosong ikut hilang, dahal its fine kalau gaada

In [85]:
import pandas as pd
import csv
from itables import show

In [86]:
books_data = pd.read_csv('data/processed/books_after_understanding.csv', low_memory=False, delimiter=';')
books_data.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 55160 entries, 0 to 55159
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   title                      55153 non-null  str
 1   gmd_name                   55157 non-null  str
 2   edition                    9127 non-null   str
 3   isbn_issn                  34936 non-null  str
 4   publisher_name             54070 non-null  str
 5   publish_year               54218 non-null  float64
 6   collation                  42145 non-null  str
 7   series_title               15 non-null     str
 8   call_number                46445 non-null  str
 9   language_name              55160 non-null  str
 10  place_name                 33749 non-null  str
 11  classification             46447 non-null  str
 12  notes                      1875 non-null   str
 13  image                      1446 non-null   str
 14  sor                        798 non-null    str
 15  authors                    52183 non-null  str
 16  topics                     24177 non-null  str
 17  item_code                  53042 non-null  str
 18  Unnamed: 18                1 non-null      str
 19  call_number_clean          46445 non-null  str
 20  call_label                 55160 non-null  str
 21  notes_word_count           55160 non-null  int64
 22  notes_word_count_category  55159 non-null  str
 23  main_title                 55151 non-null  str
 24  sub_title                  16755 non-null  str
 25  title_word_count           55160 non-null  int64
 26  item_code_normalized       53042 non-null  str
 27  first_author_last_name     52183 non-null  str
dtypes: float64(1), int64(2), str(25)
memory usage: 28.1 MB

In [87]:
books_data.drop(columns=['Unnamed: 18'], inplace=True)

In [88]:
trans_data = pd.read_csv('data/processed/trans_after_understanding.csv', low_memory=False, delimiter=';')
trans_data.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 5398 entries, 0 to 5397
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID Anggota          5398 non-null   int64
 1   Nama Anggota        5398 non-null   str
 2   Kode Eksemplar      5398 non-null   int64
 3   Judul               5398 non-null   str
 4   Tanggal Pinjam      5398 non-null   str
 5   Tanggal Kembali     5398 non-null   str
 6   Status peminjaman   5398 non-null   int64
 7   tahun_pinjam        5398 non-null   int64
 8   bulan_pinjam        5398 non-null   int64
 9   bulan_tahun_pinjam  5398 non-null   str
dtypes: int64(5), str(5)
memory usage: 892.6 KB

# Missing Value

In [89]:
clean_miss_val_df = books_data.dropna(subset=['title'])

In [90]:
clean_miss_val_df.isna().sum()

title                            0
gmd_name                         3
edition                      46026
isbn_issn                    20217
publisher_name                1086
publish_year                   938
collation                    13011
series_title                 55138
call_number                   8709
language_name                    0
place_name                   21405
classification                8707
notes                        53278
image                        53707
sor                          54355
authors                       2973
topics                       30977
item_code                     2113
call_number_clean             8709
call_label                       0
notes_word_count                 0
notes_word_count_category        1
main_title                       2
sub_title                    38398
title_word_count                 0
item_code_normalized          2113
first_author_last_name        2973
dtype: int64

In [91]:
clean_miss_val_df[clean_miss_val_df['item_code'].isna()]

,title,gmd_name,edition,isbn_issn,publisher_name,publish_year,collation,series_title,call_number,language_name,...,item_code,call_number_clean,call_label,notes_word_count,notes_word_count_category,main_title,sub_title,title_word_count,item_code_normalized,first_author_last_name
82,"pengaruh likuiditas, perputaran kas, struktur ...",Text,NaN,NaN,FAKULTAS EKONOMI DAN BISINIS UPN JATIM,2025.0,NaN,NaN,SKRIPSI EM 280/2025,Indonesia,...,NaN,SKRIPSI,Skripsi,0,0 kata,"pengaruh likuiditas, perputaran kas, struktur ...",NaN,25,NaN,Yudrinasari
131,"pengaruh pertumbuhan ekonomi, tingkat pengangg...",Text,NaN,NaN,FAKULTAS EKONOMI DAN BISNIS,2025.0,NaN,NaN,SKRIPSI EP 144/2025,Indonesia,...,NaN,SKRIPSI,Skripsi,0,0 kata,"pengaruh pertumbuhan ekonomi, tingkat pengangg...",NaN,22,NaN,Resolute
142,hubungan kausalitas impor garam dan harga dome...,Text,NaN,NaN,FAKULTAS EKONOMI DAN BISNIS,2025.0,NaN,NaN,SKRIPSI,Indonesia,...,NaN,SKRIPSI,Skripsi,0,0 kata,hubungan kausalitas impor garam dan harga dome...,NaN,9,NaN,Faisal
147,"analisis pengaruh kemiskinan, tingkat pengangg...",Text,NaN,NaN,Fakultas Ekonomi dan Bisnis UPN Jatim,2025.0,NaN,NaN,SKRIPSI EP 136/2025,Indonesia,...,NaN,SKRIPSI,Skripsi,0,0 kata,"analisis pengaruh kemiskinan, tingkat pengangg...",NaN,17,NaN,Maulana
151,pengaruh pemimpin wanita terhadap kinerja ling...,Text,NaN,NaN,Fakultas Ekonomi dan Bisnis UPN Jatim,2025.0,NaN,NaN,SKRIPSI EA 163/2025,Indonesia,...,NaN,SKRIPSI,Skripsi,0,0 kata,pengaruh pemimpin wanita terhadap kinerja ling...,NaN,11,NaN,Sakanti
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55075,html 4.01 weekend crash course,Text,NaN,979203451X,PT. Elex Media Komputindo,2002.0,"xxi, 432 p.; ill.; 23 cm.",NaN,004.678,Indonesia,...,NaN,004.678,Karya Umum,0,0 kata,html 4.01 weekend crash course,NaN,5,NaN,Perry
55144,introduction to operations research,Text,NaN,0071004920,Mc Graw Hill,1986.0,"xviii, 888 p.; ill.; 23 cm.",NaN,001.424,English,...,NaN,001.424,Karya Umum,0,0 kata,introduction to operations research,NaN,4,NaN,Hillier
55147,operations research : an introduction,Text,NaN,0024189405,Macmillan,1987.0,"xv, 876 p.; ill.; 25 cm.",NaN,001.424,English,...,NaN,001.424,Karya Umum,0,0 kata,operations research,an introduction,5,NaN,Taha
55148,operations research : an introduction,Text,NaN,002946501X,Macmillan,1992.0,"xix, 822 p.; ill.; 25 cm.",NaN,001.424,English,...,NaN,001.424,Karya Umum,0,0 kata,operations research,an introduction,5,NaN,Taha
55150,computers today,Text,NaN,007054854,Mc Graw Hill,1988.0,"xxix, 640 p.; ill.; 25 cm.",NaN,001.6,English,...,NaN,001.6,Karya Umum,0,0 kata,computers today,NaN,2,NaN,Sanders

masih ada yang bagus kayaknya bukunya, biarin aja

# Classification filter

In [92]:
upn_books_filtered = clean_miss_val_df.copy()

In [93]:
mask_1 = upn_books_filtered['classification'].str.contains('SKRIPSI', case=False, na=False)
upn_books_filtered[mask_1]

,title,gmd_name,edition,isbn_issn,publisher_name,publish_year,collation,series_title,call_number,language_name,...,item_code,call_number_clean,call_label,notes_word_count,notes_word_count_category,main_title,sub_title,title_word_count,item_code_normalized,first_author_last_name
0,pengaruh environmental social and governance (...,Text,NaN,NaN,FAKULTAS EKONOMI BISNIS UPN JATIM,2024.0,NaN,NaN,SKRIPSI EA 178/2024,Indonesia,...,<824130178>,SKRIPSI,Skripsi,0,0 kata,pengaruh environmental social and governance (...,NaN,17,['824130178'],Pramudita
3,pengaruh durasi pengoperasian membran pvc-tio2...,Text,NaN,NaN,Fakultas Teknik dan Sains UPN Veteran Jawa imur,2025.0,NaN,NaN,SKRIPSI TL 068/2025,Indonesia,...,<825340068>,SKRIPSI,Skripsi,0,0 kata,pengaruh durasi pengoperasian membran pvc-tio2...,NaN,19,['825340068'],Adjani
4,desain struktur bangunan pelimpah (spillway) p...,Text,NaN,NaN,Fakultas Teknik dan Sains UPN Veteran Jawa imur,2025.0,NaN,NaN,SKRIPSI TS 005/2025,Indonesia,...,<825350005>,SKRIPSI,Skripsi,0,0 kata,desain struktur bangunan pelimpah (spillway) p...,NaN,12,['825350005'],Prianto
5,pra rancangan pabrik asam fenil asetat dari be...,Text,NaN,NaN,Fakultas Teknik dan Sains UPN Veteran Jawa imur,2025.0,NaN,NaN,SKRIPSI TK 098/2025,Indonesia,...,<825310098>,SKRIPSI,Skripsi,0,0 kata,pra rancangan pabrik asam fenil asetat dari be...,NaN,17,['825310098'],YUNIARTI
6,pabrik urea formaldehid dari urea dan formalde...,Text,NaN,NaN,Fakultas Teknik dan Sains UPN Veteran Jawa imur,2025.0,NaN,NaN,SKRIPSI TK 097/2025,Indonesia,...,<825310097>,SKRIPSI,Skripsi,0,0 kata,pabrik urea formaldehid dari urea dan formalde...,NaN,10,['825310097'],Sari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41239,"pengaruh transparansi, akuntabilitas, dan part...",Text,NaN,NaN,Fakultas Ekonomi UPN Jatim,2023.0,"viii, 99p.; 28cm",NaN,SKRIPSI EA 036/023,Indonesia,...,<823130005>,SKRIPSI,Skripsi,0,0 kata,"pengaruh transparansi, akuntabilitas, dan part...",NaN,18,['823130005'],Nurfitri
41240,pengaruh retribusi daerah hasil pengelolaan ke...,Text,NaN,NaN,Fakultas Ekonomi Akuntansi,2023.0,"viii, 80p.; 28cm",NaN,SKRIPSI EA 035/023,Indonesia,...,<823130004>,SKRIPSI,Skripsi,0,0 kata,pengaruh retribusi daerah hasil pengelolaan ke...,NaN,25,['823130004'],Sabrina
41241,"pengaruh kejelasan anggaran sasaran, standar a...",Text,NaN,NaN,Fakultas Ekonomi Akuntansi,2023.0,"viii, 80p.; 28cm",NaN,SKRIPSI EA 033/023,Indonesia,...,<823130003>,SKRIPSI,Skripsi,0,0 kata,"pengaruh kejelasan anggaran sasaran, standar a...",NaN,17,['823130003'],Istiqfarini
41246,"pengaruh persepsi kegunaan, persepsi kemudahan...",Text,NaN,NaN,Program Sudi Administrasi Bisnis,2023.0,"xiv, hlm 108p,; 28cm",NaN,SKRIPSI ADNI 066/2023,Indonesia,...,<823420055>,SKRIPSI,Skripsi,0,0 kata,"pengaruh persepsi kegunaan, persepsi kemudahan...",NaN,16,['823420055'],Rahma
41278,"pengaruh brand image, kualitas produk dan kepe...",Text,NaN,NaN,Program Studi Administrasi Bisnis,2023.0,NaN,NaN,Skripsi ADNI 009/2023,Indonesia,...,<83795801>,Skripsi,Skripsi,174,>100 kata,"pengaruh brand image, kualitas produk dan kepe...",NaN,15,['83795801'],Andharesti

In [94]:
upn_books_filtered = upn_books_filtered[~mask_1]
upn_books_filtered['classification'].value_counts()

classification
658        960
657        689
302.2      535
658.8      387
Tesis      295
          ...
643.58       1
005.422      1
004.338      1
003.5        1
005.114      1
Name: count, Length: 8196, dtype: int64

In [95]:
mask_3 = upn_books_filtered['classification'].str.contains('tesis', case=False, na=False)
show(upn_books_filtered[mask_3])

In [96]:
upn_books_filtered = upn_books_filtered[~mask_3]
upn_books_filtered['classification'].value_counts()

classification
658        960
657        689
302.2      535
658.8      387
001.42     289
          ...
643.58       1
005.422      1
004.338      1
003.5        1
005.114      1
Name: count, Length: 8195, dtype: int64

In [97]:
upn_books_filtered['classification'].value_counts().tail(15)

classification
581.192    1
179.36     1
650.26     1
658.896    1
515.72     1
515.12     1
575.163    1
658.153    1
666.63     1
615.53     1
643.58     1
005.422    1
004.338    1
003.5      1
005.114    1
Name: count, dtype: int64

In [98]:
mask_4 = upn_books_filtered['classification'].str.contains('jurnal', case=False, na=False)
upn_books_filtered[mask_4]

,title,gmd_name,edition,isbn_issn,publisher_name,publish_year,collation,series_title,call_number,language_name,...,item_code,call_number_clean,call_label,notes_word_count,notes_word_count_category,main_title,sub_title,title_word_count,item_code_normalized,first_author_last_name
26722,bank indonesia ; statistik ekonomi keuangan da...,Text,Vol.24/No.6,11417371,Kantor Perwakilan Bank Indonesia Provinsi Jawa...,2024.0,NaN,NaN,Jurnal 0072/2024,Indonesia,...,<524020072>,Jurnal,Jurnal,0,0 kata,bank indonesia ; statistik ekonomi keuangan da...,NaN,9,['524020072'],NaN
26723,bank indonesia ; statistik ekonomi keuangan da...,Text,Vol.24/No.7,11417371,Kantor Perwakilan Bank Indonesia Provinsi Jawa...,2024.0,NaN,NaN,Jurnal 0071/2024,Indonesia,...,<524020071>,Jurnal,Jurnal,0,0 kata,bank indonesia ; statistik ekonomi keuangan da...,NaN,9,['524020071'],NaN
26724,bank indonesia ; statistik ekonomi keuangan da...,Text,Vol.24/No.4,11417371,Kantor Perwakilan Bank Indonesia Provinsi Jawa...,2024.0,NaN,NaN,Jurnal 0070/2024,Indonesia,...,<524020070>,Jurnal,Jurnal,0,0 kata,bank indonesia ; statistik ekonomi keuangan da...,NaN,9,['524020070'],NaN
26725,bank indonesia ; statistik ekonomi keuangan da...,Text,Vol.24/No.5,14117371,Bank Indonesia,2024.0,NaN,NaN,Jurnal 0069/2024,Indonesia,...,<524020069>,Jurnal,Jurnal,0,0 kata,bank indonesia ; statistik ekonomi keuangan da...,NaN,9,['524020069'],NaN
26741,brida time ; menelisik eksistensi pemerintah m...,Text,NaN,29873363,Buletin BRIDA Provinsi Jawa Timur,2024.0,NaN,NaN,JURNAL 0060/2024,Indonesia,...,<524020060>,JURNAL,Jurnal,0,0 kata,brida time ; menelisik eksistensi pemerintah m...,NaN,13,['524020060'],NaN
26831,laporan perekonomian provinsi jawa timur mei 2024,Text,Mei 2024,NaN,Bank Indonesia,2024.0,NaN,NaN,Jurnal 0053/2024,Indonesia,...,<524020053>,Jurnal,Jurnal,0,0 kata,laporan perekonomian provinsi jawa timur mei 2024,NaN,7,['524020053'],NaN
26832,statistik ekonomi keuangan daerah jawa timur o...,Text,Oktober 2023,14117371,Bank Indonesia,2023.0,NaN,NaN,Jurnal 0054/2024,Indonesia,...,<524020054>,Jurnal,Jurnal,0,0 kata,statistik ekonomi keuangan daerah jawa timur o...,NaN,8,['524020054'],NaN

In [99]:
upn_books_filtered = upn_books_filtered[~mask_4]
upn_books_filtered['classification'].value_counts()

classification
658        960
657        689
302.2      535
658.8      387
001.42     289
          ...
643.58       1
005.422      1
004.338      1
003.5        1
005.114      1
Name: count, Length: 8193, dtype: int64

In [100]:
upn_books_filtered[upn_books_filtered['classification'].str.contains('-', na=False)]['classification'].value_counts()

classification
-068        1
020-006     1
338-9STE    1
620-109     1
343-03      1
631-42      1
959-803     1
Name: count, dtype: int64

In [101]:
mask_5 = upn_books_filtered['classification'].str.contains('T.A', case=False, na=False)
show(upn_books_filtered[mask_5])

In [102]:
upn_books_filtered = upn_books_filtered[~mask_5]
upn_books_filtered['classification'].value_counts()

classification
658        960
657        689
302.2      535
658.8      387
001.42     289
          ...
643.58       1
005.422      1
004.338      1
003.5        1
005.114      1
Name: count, Length: 8190, dtype: int64

In [103]:
show(upn_books_filtered[upn_books_filtered['classification'].str.contains('/', na=False)]['classification'].value_counts())

oke pretty nice

In [104]:
upn_books_filtered.info()

<class 'pandas.DataFrame'>
Index: 44301 entries, 1 to 55159
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   title                      44301 non-null  str
 1   gmd_name                   44298 non-null  str
 2   edition                    8928 non-null   str
 3   isbn_issn                  34917 non-null  str
 4   publisher_name             43314 non-null  str
 5   publish_year               43431 non-null  float64
 6   collation                  42067 non-null  str
 7   series_title               14 non-null     str
 8   call_number                35593 non-null  str
 9   language_name              44301 non-null  str
 10  place_name                 23003 non-null  str
 11  classification             35594 non-null  str
 12  notes                      1560 non-null   str
 13  image                      1446 non-null   str
 14  sor                        134 non-null    str
 15  authors                    41359 non-null  str
 16  topics                     23056 non-null  str
 17  item_code                  42361 non-null  str
 18  call_number_clean          35593 non-null  str
 19  call_label                 44301 non-null  str
 20  notes_word_count           44301 non-null  int64
 21  notes_word_count_category  44300 non-null  str
 22  main_title                 44301 non-null  str
 23  sub_title                  16156 non-null  str
 24  title_word_count           44301 non-null  int64
 25  item_code_normalized       42361 non-null  str
 26  first_author_last_name     41359 non-null  str
dtypes: float64(1), int64(2), str(24)
memory usage: 21.1 MB

In [105]:
upn_books_filtered.isna().sum()

title                            0
gmd_name                         3
edition                      35373
isbn_issn                     9384
publisher_name                 987
publish_year                   870
collation                     2234
series_title                 44287
call_number                   8708
language_name                    0
place_name                   21298
classification                8707
notes                        42741
image                        42855
sor                          44167
authors                       2942
topics                       21245
item_code                     1940
call_number_clean             8708
call_label                       0
notes_word_count                 0
notes_word_count_category        1
main_title                       0
sub_title                    28145
title_word_count                 0
item_code_normalized          1940
first_author_last_name        2942
dtype: int64

# Language Filter

In [106]:
mask = upn_books_filtered['language_name'] == 'Dutch'
upn_books_filtered[mask]

,title,gmd_name,edition,isbn_issn,publisher_name,publish_year,collation,series_title,call_number,language_name,...,item_code,call_number_clean,call_label,notes_word_count,notes_word_count_category,main_title,sub_title,title_word_count,item_code_normalized,first_author_last_name
3691,"deleuze and marx : deleuze studies, volume 3: ...",Electronic Resource,NaN,9781474469555,Edinburgh University Press (EUP),2019.0,149,NaN,194,Dutch,...,<618182>,194,Filsafat,210,>100 kata,deleuze and marx,"deleuze studies, volume 3: 2009 (supplement)",10,['618182'],Jain
5663,"sagaing district (burma gazetteer), volume b",Electronic Resource,NaN,NaN,Heritage Books of Asia,1913.0,51,NaN,NaN,Dutch,...,<615969>,NaN,Lainnya,0,0 kata,"sagaing district (burma gazetteer), volume b",NaN,6,['615969'],NaN
5665,"upper chindwin district (burma gazetteer), vol...",Electronic Resource,NaN,NaN,Heritage Books of Asia,1913.0,64,NaN,NaN,Dutch,...,<615971>,NaN,Lainnya,0,0 kata,"upper chindwin district (burma gazetteer), vol...",NaN,7,['615971'],NaN
5738,"burma gazetteer: upper chindwin district, volu...",Electronic Resource,NaN,NaN,Heritage Books of Asia,1913.0,142,NaN,NaN,Dutch,...,<616045>,NaN,Lainnya,0,0 kata,burma gazetteer,"upper chindwin district, volume a",7,['616045'],Brown
5871,the talaings,Electronic Resource,NaN,NaN,Heritage Books of Asia,1917.0,193,NaN,NaN,Dutch,...,<616187>,NaN,Lainnya,0,0 kata,the talaings,NaN,2,['616187'],Halliday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52398,de wetboeken wetten en verordeningen benevens ...,Text,text,NaN,NaN,1989.0,1540 p.; 20 cm.,NaN,348.025 9,Dutch,...,<90241901>,348.025,Ilmu Sosial,0,0 kata,de wetboeken wetten en verordeningen benevens ...,NaN,12,['90241901'],NaN
52669,fundamentals of college algebra,Text,text,0817503085,"Prindle, Weben & Schmidt",1981.0,"x, 385 p.; ill.; 24 cm.",NaN,512.9,Dutch,...,<90291301>,512.9,Ilmu Pengetahuan Murni,0,0 kata,fundamentals of college algebra,NaN,4,['90291301'],Swokowski
54070,circuirs,Text,NaN,007065591X,Mc Graw Hill,1977.0,"ix, 820 p.; ill.; ind.; 21 cm.",NaN,621.3,Dutch,...,<90063001>,621.3,Ilmu Pengetahuan Terapan/Teknologi,0,0 kata,circuirs,NaN,1,['90063001'],Tuttle
54453,aileen reid,Text,NaN,1858411378,"Bison Books, ltd",1995.0,112p.; ill.; 35 cm.,NaN,658.403,Dutch,...,<90121201>,658.403,Ilmu Pengetahuan Terapan/Teknologi,0,0 kata,aileen reid,NaN,2,['90121201'],Pei
55059,college algebra,Text,NaN,NaN,John Wiley & Sons,1961.0,"xvi, 440p.; ill.; ind.; 23 cm.",NaN,657.024,Dutch,...,<90208801>,657.024,Ilmu Pengetahuan Terapan/Teknologi,0,0 kata,college algebra,NaN,2,['90208801'],Leonhardy

In [107]:
upn_books_filtered = upn_books_filtered[~mask]

In [108]:
upn_books_filtered['language_name'].value_counts()

language_name
English      24642
Indonesia    18476
Name: count, dtype: int64

In [109]:
upn_books_filtered.info()

<class 'pandas.DataFrame'>
Index: 43118 entries, 1 to 55159
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   title                      43118 non-null  str
 1   gmd_name                   43115 non-null  str
 2   edition                    8393 non-null   str
 3   isbn_issn                  33877 non-null  str
 4   publisher_name             42138 non-null  str
 5   publish_year               42261 non-null  float64
 6   collation                  40893 non-null  str
 7   series_title               14 non-null     str
 8   call_number                35165 non-null  str
 9   language_name              43118 non-null  str
 10  place_name                 22987 non-null  str
 11  classification             35166 non-null  str
 12  notes                      1556 non-null   str
 13  image                      1441 non-null   str
 14  sor                        134 non-null    str
 15  authors                    40215 non-null  str
 16  topics                     23030 non-null  str
 17  item_code                  41181 non-null  str
 18  call_number_clean          35165 non-null  str
 19  call_label                 43118 non-null  str
 20  notes_word_count           43118 non-null  int64
 21  notes_word_count_category  43117 non-null  str
 22  main_title                 43118 non-null  str
 23  sub_title                  15600 non-null  str
 24  title_word_count           43118 non-null  int64
 25  item_code_normalized       41181 non-null  str
 26  first_author_last_name     40215 non-null  str
dtypes: float64(1), int64(2), str(24)
memory usage: 20.6 MB

# Duplicates

In [110]:
upn_drop_duplicate = upn_books_filtered.copy()

In [111]:
upn_drop_duplicate.duplicated().sum()

np.int64(1)

In [112]:
upn_drop_duplicate = upn_drop_duplicate.drop_duplicates()
upn_drop_duplicate.duplicated().sum()

np.int64(0)

## titles

In [113]:
upn_drop_duplicate[upn_drop_duplicate['title'].str.contains('Computers today', case=False, na=False)]

,title,gmd_name,edition,isbn_issn,publisher_name,publish_year,collation,series_title,call_number,language_name,...,item_code,call_number_clean,call_label,notes_word_count,notes_word_count_category,main_title,sub_title,title_word_count,item_code_normalized,first_author_last_name
55149,computers today,Text,NaN,0070547017,Mc Graw Hill,1985.0,"xxi, 648 p.; ill.; 24 cm.",NaN,001.64,English,...,<90004801>,001.64,Karya Umum,0,0 kata,computers today,NaN,2,['90004801'],Sanders
55150,computers today,Text,NaN,007054854,Mc Graw Hill,1988.0,"xxix, 640 p.; ill.; 25 cm.",NaN,001.6,English,...,NaN,001.6,Karya Umum,0,0 kata,computers today,NaN,2,NaN,Sanders

duplikasi data karena ada buku versi yang lebih baru ??

In [114]:
upn_drop_duplicate['first_author_last_name'] = (upn_drop_duplicate['first_author_last_name'].str.lower())

In [115]:
upn_drop_duplicate.duplicated(subset=['title']).sum()

np.int64(10108)

In [116]:
upn_drop_duplicate.duplicated(subset=['title', 'authors']).sum()

np.int64(6396)

In [117]:
upn_drop_duplicate.duplicated(subset=['title', 'first_author_last_name']).sum()

np.int64(6841)

In [118]:
upn_drop_duplicate.duplicated(subset=['title', 'isbn_issn']).sum()

np.int64(6470)

In [119]:
upn_drop_duplicate.duplicated(subset=['title', 'authors', 'isbn_issn']).sum()

np.int64(5535)

In [120]:
upn_drop_duplicate.duplicated(subset=['title', 'authors', 'first_author_last_name','isbn_issn']).sum()

np.int64(5530)

In [121]:
show(upn_drop_duplicate[upn_drop_duplicate.duplicated(subset=['title', 'isbn_issn'], keep=False)][['title', 'authors', 'isbn_issn', 'item_code_normalized']])

In [ ]:
import ast
import numpy as np

# Fungsi untuk mengonversi string menjadi list
def str_to_list(val):
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return []
    
    if isinstance(val, list):
        return val
    
    if isinstance(val, (np.ndarray, pd.Series)):
        return val.tolist()
    
    if isinstance(val, str):
        val = val.strip()
        if val.startswith('[') and val.endswith(']'):
            try:
                return ast.literal_eval(val)
            except:
                return [val]  
        else:
            return [val]
    
    return [val]

In [123]:
upn_drop_duplicate['item_code_normalized'] = upn_drop_duplicate['item_code_normalized'].apply(str_to_list)
upn_drop_duplicate['topics'] = upn_drop_duplicate['topics'].apply(str_to_list)

In [ ]:
def drop_book_duplicates_combined(df):
    df = df.copy()
    keys = ['title', 'authors', 'isbn_issn', 'first_author_last_name']
    
    for col in keys:
        if col in df.columns:
            df[f'{col}_tmp'] = df[col].astype(str).str.lower().str.strip()
            df[f'{col}_tmp'] = df[f'{col}_tmp'].replace(['nan', 'none', '', '__unknown_author__'], 'unknown')

    # menghitung jumlah kolom yang tidak kosong
    df['info_count'] = df.notna().sum(axis=1)

    mask_unknown = df['authors'].isna()
    # Agar data yang tidak ada nama penulis berada di bawah
    df.loc[mask_unknown, 'info_count'] -= 10

    if 'authors' in df.columns:
        mask_unknown = (df['authors'].isna()) | \
            (df['authors'].astype(str).str.lower().str.contains('unknown', na=False))
        df.loc[mask_unknown, 'info_count'] -= 10

    tmp_keys = [f'{c}_tmp' for c in keys if f'{c}_tmp' in df.columns]
    # Pengurutan data menggunakan skor data yang tidak kosong
    df = df.sort_values(by=tmp_keys + ['info_count'], ascending=[True] * len(tmp_keys) + [False])

    # Fungsi untuk menggabungkan data list pada kolom kode_buku dan topik
    def combine_lists(series):
        combined = []
        for val in series:
            if isinstance(val, list):
                combined.extend(val)
            elif pd.notna(val):
                combined.append(val)
        seen = set()
        result = []
        for x in combined:
            if x not in seen:
                seen.add(x)
                result.append(x)
        return result if result else None

    group_cols_list = [
        ['title_tmp', 'isbn_issn_tmp'],
        ['title_tmp', 'first_author_last_name_tmp'],
        ['isbn_issn_tmp', 'authors_tmp'],
        ['isbn_issn_tmp', 'first_author_last_name_tmp']
    ]

    for group_cols in group_cols_list:
        # Penggabungan data kode_buku dan topik
        agg_dict = {
            'item_code_normalized': combine_lists,
            'topics': combine_lists
        }
        # data yang lainnya
        other_cols = [c for c in df.columns if c not in group_cols + ['item_code_normalized', 'topik']]
        for col in other_cols:
            agg_dict[col] = 'first'
        
        # Penggabungan data yang sama untuk menghilangkan duplikasi
        df = df.groupby(group_cols, dropna=False).agg(agg_dict).reset_index()

    # Menghapus kolom sementara
    cols_to_drop = [f'{c}_tmp' for c in keys if f'{c}_tmp' in df.columns] + ['info_count']
    df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])
    
    return df

In [125]:
upn_drop_duplicate = drop_book_duplicates_combined(upn_drop_duplicate)
show(upn_drop_duplicate[upn_drop_duplicate.duplicated(subset=['title'], keep=False)][['title', 'authors', 'first_author_last_name', 'isbn_issn', 'item_code_normalized']])

In [126]:
upn_drop_duplicate.info()

<class 'pandas.DataFrame'>
RangeIndex: 29770 entries, 0 to 29769
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   item_code_normalized       29134 non-null  object
 1   topics                     29770 non-null  object
 2   title                      29770 non-null  str
 3   gmd_name                   29768 non-null  str
 4   edition                    6495 non-null   str
 5   isbn_issn                  26489 non-null  str
 6   publisher_name             29110 non-null  str
 7   publish_year               29262 non-null  float64
 8   collation                  28208 non-null  str
 9   series_title               14 non-null     str
 10  call_number                25846 non-null  str
 11  language_name              29770 non-null  str
 12  place_name                 17110 non-null  str
 13  classification             25847 non-null  str
 14  notes                      1232 non-null   str
 15  image                      1299 non-null   str
 16  sor                        59 non-null     str
 17  authors                    28449 non-null  str
 18  item_code                  29134 non-null  str
 19  call_number_clean          25846 non-null  str
 20  call_label                 29770 non-null  str
 21  notes_word_count           29770 non-null  int64
 22  notes_word_count_category  29769 non-null  str
 23  main_title                 29770 non-null  str
 24  sub_title                  10587 non-null  str
 25  title_word_count           29770 non-null  int64
 26  first_author_last_name     28449 non-null  str
dtypes: float64(1), int64(2), object(2), str(22)
memory usage: 13.4+ MB

In [127]:
show(upn_drop_duplicate[upn_drop_duplicate.duplicated(subset=['title'], keep=False)][['title', 'authors', 'first_author_last_name', 'isbn_issn', 'item_code_normalized']])

In [128]:
upn_drop_duplicate[upn_drop_duplicate['title'].str.contains('Computers today', case=False, na=False)]

,item_code_normalized,topics,title,gmd_name,edition,isbn_issn,publisher_name,publish_year,collation,series_title,...,authors,item_code,call_number_clean,call_label,notes_word_count,notes_word_count_category,main_title,sub_title,title_word_count,first_author_last_name
481,[90004801],[electronic data processing],computers today,Text,NaN,0070547017,Mc Graw Hill,1985.0,"xxi, 648 p.; ill.; 24 cm.",NaN,...,Donald H. Sanders,<90004801>,001.64,Karya Umum,0,0 kata,computers today,NaN,2,sanders

In [129]:
upn_drop_duplicate.duplicated(subset=['title']).sum()

np.int64(1917)

In [130]:
upn_drop_duplicate.info()

<class 'pandas.DataFrame'>
RangeIndex: 29770 entries, 0 to 29769
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   item_code_normalized       29134 non-null  object
 1   topics                     29770 non-null  object
 2   title                      29770 non-null  str
 3   gmd_name                   29768 non-null  str
 4   edition                    6495 non-null   str
 5   isbn_issn                  26489 non-null  str
 6   publisher_name             29110 non-null  str
 7   publish_year               29262 non-null  float64
 8   collation                  28208 non-null  str
 9   series_title               14 non-null     str
 10  call_number                25846 non-null  str
 11  language_name              29770 non-null  str
 12  place_name                 17110 non-null  str
 13  classification             25847 non-null  str
 14  notes                      1232 non-null   str
 15  image                      1299 non-null   str
 16  sor                        59 non-null     str
 17  authors                    28449 non-null  str
 18  item_code                  29134 non-null  str
 19  call_number_clean          25846 non-null  str
 20  call_label                 29770 non-null  str
 21  notes_word_count           29770 non-null  int64
 22  notes_word_count_category  29769 non-null  str
 23  main_title                 29770 non-null  str
 24  sub_title                  10587 non-null  str
 25  title_word_count           29770 non-null  int64
 26  first_author_last_name     28449 non-null  str
dtypes: float64(1), int64(2), object(2), str(22)
memory usage: 13.4+ MB

## item code

In [131]:
upn_drop_duplicate[upn_drop_duplicate['item_code'].isna()]

,item_code_normalized,topics,title,gmd_name,edition,isbn_issn,publisher_name,publish_year,collation,series_title,...,authors,item_code,call_number_clean,call_label,notes_word_count,notes_word_count_category,main_title,sub_title,title_word_count,first_author_last_name
14,None,[biological chemistry],introduction to organic and biological chemistry,Text,NaN,0023065702,Macmillan,1978.0,"xiii,514 p.;ill.;ind.; 24cm",NaN,...,Stuart J. Baum,NaN,621.381,Ilmu Pengetahuan Terapan/Teknologi,0,0 kata,introduction to organic and biological chemistry,NaN,6,baum
34,None,"[chemistry, physical and theoretical]",physical chemistry,Text,text,0023397608,Macmillan,1977.0,"xix, 983p.; ill.; ind.; 25 cm.",NaN,...,Vojtech Fried,NaN,541.3,Ilmu Pengetahuan Murni,0,0 kata,physical chemistry,NaN,2,fried
37,None,[investments],investments : analysis and management,Text,text,0023527102,Macmillan Publishing,1976.0,"ix, 574p.; ill.; ind.; 23cm.",NaN,...,Douglas A. Hayes,NaN,332.67,Ilmu Sosial,0,0 kata,investments,analysis and management,5,hayes
38,None,[marketing],marketing,Text,text,0023539402,Macmillan,1976.0,"xiii, 610p.; ill.; ind.; 23 cm.",NaN,...,James L. Heskett,NaN,658.8,Ilmu Pengetahuan Terapan/Teknologi,0,0 kata,marketing,NaN,1,heskett
62,None,[international economics relations],international economics,Text,text,0024053813,Prentice Hall,1995.0,"xxxvii, 778 p.; ill.; ind.; 23 cm.",NaN,...,Dominick Salvatore,NaN,337,Ilmu Sosial,0,0 kata,international economics,NaN,2,salvatore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29616,None,"[sociology, popular culture, media and communi...",games without frontiers?,Electronic Resource,NaN,NaN,Palgrave Macmillan Cham,2021.0,NaN,NaN,...,Heather Wardle,NaN,NaN,Lainnya,0,0 kata,games without frontiers?,NaN,3,wardle
29683,None,"[audio-visual culture, music]",when music takes over in film,Electronic Resource,NaN,NaN,Palgrave Macmillan Cham,2023.0,NaN,NaN,...,"Anna K. Windisch, Claus Tieber, Phil Powrie",NaN,NaN,Lainnya,0,0 kata,when music takes over in film,NaN,6,windisch
29701,None,[english language - dictionaries],kamus umum inggris - indonesia,Text,text,NaN,CV. Pengarang,1982.0,NaN,NaN,...,S. Wojowasito,NaN,423,Bahasa,0,0 kata,kamus umum inggris - indonesia,NaN,5,wojowasito
29714,None,[colonial american history],the making of an imperial polity,Electronic Resource,NaN,NaN,Cambridge University Press,2020.0,NaN,NaN,...,Lauren Working,NaN,NaN,Lainnya,0,0 kata,the making of an imperial polity,NaN,6,working
29744,None,"[popular culture, youth culture, asian culture]",diasporic hallyu,Electronic Resource,NaN,NaN,Palgrave Macmillan Cham,2022.0,NaN,NaN,...,Kyong Yoon,NaN,NaN,Lainnya,0,0 kata,diasporic hallyu,NaN,2,yoon

## isbn

In [132]:
isbn_counts = upn_drop_duplicate['isbn_issn'].value_counts()
more_than_one_isbn_counts = isbn_counts[isbn_counts > 1]
more_than_one_isbn_counts

isbn_issn
9795140302        10
08534470           6
9786022170457      6
97897951865159     6
9789797694173      6
                  ..
9799917652         2
9799917654         2
9799998409         2
9812561056         2
9813046015         2
Name: count, Length: 813, dtype: int64

In [133]:
show(upn_drop_duplicate[upn_drop_duplicate['isbn_issn'].isin(more_than_one_isbn_counts.index)][['title', 'authors', 'first_author_last_name', 'isbn_issn']])

In [134]:
upn_drop_duplicate[['title', 'authors', 'isbn_issn']].duplicated().sum()

np.int64(0)

In [135]:
upn_drop_duplicate.drop_duplicates(subset=['title', 'authors', 'isbn_issn'], keep='first', inplace=True)

In [136]:
upn_drop_duplicate.info()

<class 'pandas.DataFrame'>
RangeIndex: 29770 entries, 0 to 29769
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   item_code_normalized       29134 non-null  object
 1   topics                     29770 non-null  object
 2   title                      29770 non-null  str
 3   gmd_name                   29768 non-null  str
 4   edition                    6495 non-null   str
 5   isbn_issn                  26489 non-null  str
 6   publisher_name             29110 non-null  str
 7   publish_year               29262 non-null  float64
 8   collation                  28208 non-null  str
 9   series_title               14 non-null     str
 10  call_number                25846 non-null  str
 11  language_name              29770 non-null  str
 12  place_name                 17110 non-null  str
 13  classification             25847 non-null  str
 14  notes                      1232 non-null   str
 15  image                      1299 non-null   str
 16  sor                        59 non-null     str
 17  authors                    28449 non-null  str
 18  item_code                  29134 non-null  str
 19  call_number_clean          25846 non-null  str
 20  call_label                 29770 non-null  str
 21  notes_word_count           29770 non-null  int64
 22  notes_word_count_category  29769 non-null  str
 23  main_title                 29770 non-null  str
 24  sub_title                  10587 non-null  str
 25  title_word_count           29770 non-null  int64
 26  first_author_last_name     28449 non-null  str
dtypes: float64(1), int64(2), object(2), str(22)
memory usage: 13.4+ MB

# Deskripsi

In [137]:
books_desc = upn_drop_duplicate.copy()

In [138]:
show(books_desc[books_desc['notes'].notna()]['notes'])

In [139]:
books_desc['deskripsi'] = books_desc['notes']

In [140]:
books_desc['notes_word_count_category'].value_counts()

notes_word_count_category
0 kata         28757
1-3 kata         778
>100 kata        168
51-100 kata       33
21-50 kata        24
4-10 kata          6
11-20 kata         3
Name: count, dtype: int64

In [141]:
books_desc['notes_word_count'].value_counts().sort_index().head(10)

notes_word_count
0     28757
1       776
3         2
4         2
5         1
6         2
7         1
19        1
20        2
21        1
Name: count, dtype: int64

In [142]:
show(books_desc[books_desc['notes_word_count_category'] == '4-10 kata']['notes'])

deksripsi ideal di data ini lebih dari 10 kata

In [143]:
mask = books_desc['notes_word_count'] <= 10
books_desc.loc[mask, 'deskripsi'] = None
books_desc['deskripsi'].notna().sum()

np.int64(229)

In [144]:
books_desc['deskripsi'] = (books_desc['deskripsi'].str.lower())

In [145]:
books_desc[books_desc['deskripsi'].notna()]['deskripsi'].sample(5)

20559    the malaysian economy is at a crossroads amid ...
9878     bold, visual, profound, symbolic: japanese kan...
6200     considers the emotional and relational implica...
12152    a new account of globalization’s decline as th...
8925     examines western-inspired fashion objects in j...
Name: deskripsi, dtype: str

# publish year

In [146]:
books_year = books_desc.copy()
books_year['publish_year'].value_counts()

publish_year
2019.0    1897
2024.0    1074
2023.0    1052
2017.0     994
2006.0     991
          ...
1849.0       1
1847.0       1
1800.0       1
1828.0       1
1862.0       1
Name: count, Length: 238, dtype: int64

In [147]:
mask = books_year['publish_year'] < 1500
show(books_year[mask][['title', 'publish_year']])

In [148]:
books_year.loc[mask, 'publish_year'] = None
books_year[mask]['publish_year'].value_counts()

Series([], Name: count, dtype: int64)

In [149]:
books_year['publish_year'].value_counts().sort_index().head(10)

publish_year
1690.0    1
1712.0    1
1739.0    1
1753.0    1
1755.0    1
1757.0    1
1762.0    1
1770.0    1
1775.0    1
1782.0    2
Name: count, dtype: int64

In [150]:
books_year[books_year['publish_year'] == 1690.0]

,item_code_normalized,topics,title,gmd_name,edition,isbn_issn,publisher_name,publish_year,collation,series_title,...,item_code,call_number_clean,call_label,notes_word_count,notes_word_count_category,main_title,sub_title,title_word_count,first_author_last_name,deskripsi
27351,"[607221, 605720]",[],a full and true relation of the great and wond...,Electronic Resource,NaN,NaN,IG Library,1690.0,42,NaN,...,<607221>,NaN,Lainnya,0,0 kata,a full and true relation of the great and wond...,giving a particular account of the seizing and...,45,frafer.,NaN

# ISBN

In [151]:
books_year[books_year['isbn_issn'].str.contains(' ')]
books_year['isbn_issn'] = books_year['isbn_issn'].str.replace(' ', '')
books_year['isbn_issn'].str.contains(' ').sum()

np.int64(0)

# Book Format Check

In [152]:
books_year.info()

<class 'pandas.DataFrame'>
RangeIndex: 29770 entries, 0 to 29769
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   item_code_normalized       29134 non-null  object
 1   topics                     29770 non-null  object
 2   title                      29770 non-null  str
 3   gmd_name                   29768 non-null  str
 4   edition                    6495 non-null   str
 5   isbn_issn                  26489 non-null  str
 6   publisher_name             29110 non-null  str
 7   publish_year               29088 non-null  float64
 8   collation                  28208 non-null  str
 9   series_title               14 non-null     str
 10  call_number                25846 non-null  str
 11  language_name              29770 non-null  str
 12  place_name                 17110 non-null  str
 13  classification             25847 non-null  str
 14  notes                      1232 non-null   str
 15  image                      1299 non-null   str
 16  sor                        59 non-null     str
 17  authors                    28449 non-null  str
 18  item_code                  29134 non-null  str
 19  call_number_clean          25846 non-null  str
 20  call_label                 29770 non-null  str
 21  notes_word_count           29770 non-null  int64
 22  notes_word_count_category  29769 non-null  str
 23  main_title                 29770 non-null  str
 24  sub_title                  10587 non-null  str
 25  title_word_count           29770 non-null  int64
 26  first_author_last_name     28449 non-null  str
 27  deskripsi                  229 non-null    str
dtypes: float64(1), int64(2), object(2), str(23)
memory usage: 13.8+ MB

# Riwayat

In [153]:
trans_cleaned = trans_data.copy()

In [154]:
trans_cleaned.duplicated(subset=['ID Anggota','Kode Eksemplar', 'Tanggal Pinjam']).sum()

np.int64(26)

In [155]:
trans_cleaned.sort_values(by=['Tanggal Pinjam'], inplace=True)
trans_cleaned

,ID Anggota,Nama Anggota,Kode Eksemplar,Judul,Tanggal Pinjam,Tanggal Kembali,Status peminjaman,tahun_pinjam,bulan_pinjam,bulan_tahun_pinjam
0,196903132021211000,"Fatchullah, S.Sos, M.A",91185703,Kalkulus buku 1,2023-09-08,2023-09-15,1,2023,9,2023-09
1,20081010235,20081010235,91185703,Kalkulus buku 1,2023-09-08,2023-09-15,1,2023,9,2023-09
2,196903132021211000,"Fatchullah, S.Sos, M.A",91185703,Kalkulus buku 1,2023-09-10,2023-09-17,1,2023,9,2023-09
3,196903132021211000,"Fatchullah, S.Sos, M.A",90916701,Riset Operasi dan Ekonofisika (operation rese...,2023-09-11,2023-09-18,1,2023,9,2023-09
187,22031010134,DAMARA RAMADHANI MARITZA,90271402,Elements of organic chemistry,2023-09-11,2023-09-18,1,2023,9,2023-09
...,...,...,...,...,...,...,...,...,...,...
5393,22013010294,WIDYA FRAHESTIKA,91554701,Akuntansi Keuangan Daerah Berbasis Akrual,2025-11-17,2025-11-24,0,2025,11,2025-11
5394,23013010026,Zidan Ardiansyah,90366601,"Pengantar ekonomi, jilid 2",2025-11-17,2025-11-24,0,2025,11,2025-11
5395,22012010010,KANIA LUTHFIYYAH,91028503,Bank and financial institution management conv...,2025-11-18,2025-11-25,0,2025,11,2025-11
5396,25013010324,ANGGUN ARTIKA DEWI,90884701,Mengenal bebrapa uji statistik dalam penelitian,2025-11-18,2025-11-25,0,2025,11,2025-11
5397,25013010324,ANGGUN ARTIKA DEWI,91150201,"Akuntansi, Jilid 1",2025-11-18,2025-11-25,0,2025,11,2025-11

In [156]:
show(trans_cleaned[trans_cleaned.duplicated(subset=['ID Anggota','Kode Eksemplar', 'Tanggal Pinjam'], keep=False)][['ID Anggota', 'Kode Eksemplar', 'Tanggal Pinjam']])

In [157]:
trans_cleaned = trans_cleaned.drop_duplicates(subset=['ID Anggota','Kode Eksemplar', 'Tanggal Pinjam'], keep='first')

In [158]:
show(trans_cleaned[trans_cleaned.duplicated(subset=['ID Anggota','Kode Eksemplar', 'Tanggal Pinjam'], keep=False)][['ID Anggota', 'Kode Eksemplar', 'Tanggal Pinjam']])

In [159]:
trans_cleaned.isna().sum()

ID Anggota            0
Nama Anggota          0
Kode Eksemplar        0
Judul                 0
Tanggal Pinjam        0
Tanggal Kembali       0
Status peminjaman     0
tahun_pinjam          0
bulan_pinjam          0
bulan_tahun_pinjam    0
dtype: int64

# Output

## book

In [160]:
book_after_clean = books_year
book_after_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 29770 entries, 0 to 29769
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   item_code_normalized       29134 non-null  object
 1   topics                     29770 non-null  object
 2   title                      29770 non-null  str
 3   gmd_name                   29768 non-null  str
 4   edition                    6495 non-null   str
 5   isbn_issn                  26489 non-null  str
 6   publisher_name             29110 non-null  str
 7   publish_year               29088 non-null  float64
 8   collation                  28208 non-null  str
 9   series_title               14 non-null     str
 10  call_number                25846 non-null  str
 11  language_name              29770 non-null  str
 12  place_name                 17110 non-null  str
 13  classification             25847 non-null  str
 14  notes                      1232 non-null   str
 15  image                      1299 non-null   str
 16  sor                        59 non-null     str
 17  authors                    28449 non-null  str
 18  item_code                  29134 non-null  str
 19  call_number_clean          25846 non-null  str
 20  call_label                 29770 non-null  str
 21  notes_word_count           29770 non-null  int64
 22  notes_word_count_category  29769 non-null  str
 23  main_title                 29770 non-null  str
 24  sub_title                  10587 non-null  str
 25  title_word_count           29770 non-null  int64
 26  first_author_last_name     28449 non-null  str
 27  deskripsi                  229 non-null    str
dtypes: float64(1), int64(2), object(2), str(23)
memory usage: 13.8+ MB

In [161]:
book_output = pd.DataFrame()

In [162]:
book_output['kode_buku'] = book_after_clean['item_code_normalized']
book_output['isbn_issn'] =  book_after_clean['isbn_issn']
book_output['judul_buku'] = book_after_clean['main_title']
book_output['subjudul'] = book_after_clean['sub_title']
book_output['penulis'] = book_after_clean['authors']
book_output['nama_belakang'] = book_after_clean['first_author_last_name']
book_output['topik'] = book_after_clean['topics']
book_output['deskripsi'] = book_after_clean['deskripsi']
book_output['bahasa'] = book_after_clean['language_name']
book_output['kategori'] = book_after_clean['call_label']
book_output['tahun_terbit'] = book_after_clean['publish_year']
book_output.sample(3)

,kode_buku,isbn_issn,judul_buku,subjudul,penulis,nama_belakang,topik,deskripsi,bahasa,kategori,tahun_terbit
7435,[617299],9781474410502,natural catastrophe,climate change and neoliberal governance,Brian Elliott,elliott,[],NaN,English,Ilmu Sosial,2016.0
25186,[90195301],9798012968,indeks hasil penelitian dan karya ilmiah,NaN,Pdii-Lipi,pdii-lipi,[research - index],NaN,Indonesia,Ilmu Pengetahuan Terapan/Teknologi,1992.0
855,"[90672301, 90672302]",0130006122,the abcs of microcomputers,a computer literacy primer,Linda Gail Christie,christie,[microcomputers],NaN,English,Karya Umum,1983.0

In [163]:
book_output['kode_buku'] = (book_output['kode_buku'].fillna('', inplace=True))
book_output['isbn_issn'] = (book_output['isbn_issn'].fillna('', inplace=True))
book_output['judul_buku'] = (book_output['judul_buku'].fillna('', inplace=True))
book_output['subjudul'] = (book_output['subjudul'].fillna('', inplace=True))
book_output['penulis'] = (book_output['penulis'].fillna('', inplace=True))
book_output['nama_belakang'] = (book_output['nama_belakang'].fillna('', inplace=True))
book_output['topik'] = (book_output['topik'].fillna('', inplace=True))
book_output['deskripsi'] = (book_output['deskripsi'].fillna('', inplace=True))
book_output['bahasa'] = (book_output['bahasa'].fillna('', inplace=True))
book_output['kategori'] = (book_output['kategori'].fillna('', inplace=True))
book_output['tahun_terbit'] = book_after_clean['publish_year']

C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['kode_buku'] = (book_output['kode_buku'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['isbn_issn'] = (book_output['isbn_issn'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['judul_buku'] = (book_output['judul_buku'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['subjudul'] = (book_output['subjudul'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['penulis'] = (book_output['penulis'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['nama_belakang'] = (book_output['nama_belakang'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['topik'] = (book_output['topik'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['deskripsi'] = (book_output['deskripsi'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:9: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['bahasa'] = (book_output['bahasa'].fillna('', inplace=True))
C:\Users\reera\AppData\Local\Temp\ipykernel_18064\3904930685.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  book_output['kategori'] = (book_output['kategori'].fillna('', inplace=True))

In [164]:
book_output.info()

<class 'pandas.DataFrame'>
RangeIndex: 29770 entries, 0 to 29769
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   kode_buku      29770 non-null  object
 1   isbn_issn      29770 non-null  str
 2   judul_buku     29770 non-null  str
 3   subjudul       29770 non-null  str
 4   penulis        29770 non-null  str
 5   nama_belakang  29770 non-null  str
 6   topik          29770 non-null  object
 7   deskripsi      29770 non-null  str
 8   bahasa         29770 non-null  str
 9   kategori       29770 non-null  str
 10  tahun_terbit   29088 non-null  float64
dtypes: float64(1), object(2), str(8)
memory usage: 5.8+ MB

In [165]:
VERSION = '4'

book_output.to_csv(f'data/processed/books_after_cleaning_{VERSION}.csv', index=False)

## trans

In [166]:
trans_output = trans_cleaned.copy()
trans_output.info()

<class 'pandas.DataFrame'>
Index: 5372 entries, 0 to 5397
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID Anggota          5372 non-null   int64
 1   Nama Anggota        5372 non-null   str
 2   Kode Eksemplar      5372 non-null   int64
 3   Judul               5372 non-null   str
 4   Tanggal Pinjam      5372 non-null   str
 5   Tanggal Kembali     5372 non-null   str
 6   Status peminjaman   5372 non-null   int64
 7   tahun_pinjam        5372 non-null   int64
 8   bulan_pinjam        5372 non-null   int64
 9   bulan_tahun_pinjam  5372 non-null   str
dtypes: int64(5), str(5)
memory usage: 933.5 KB

In [167]:
trans_output.drop(columns=['Tanggal Kembali', 'Status peminjaman'], inplace=True)

In [168]:
trans_output.to_csv('data/processed/trans_after_cleaning.csv', index=False)