## init

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

from collections import defaultdict

BATCH_SIZE = 128
MAX_CONTEXT_LENGTH = 10
PAD_ITEM_ID = 0

# Ids

## books

In [2]:
books = pd.read_csv('data/processed/books_enriched.csv', low_memory=False, delimiter=';')
books.info()

<class 'pandas.DataFrame'>
RangeIndex: 14502 entries, 0 to 14501
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   kode_buku                 14502 non-null  str
 1   isbn_issn                 12794 non-null  str
 2   judul_buku                14502 non-null  str
 3   subjudul                  7818 non-null   str
 4   penulis                   13490 non-null  str
 5   nama_belakang             13838 non-null  str
 6   topik                     13806 non-null  str
 7   deskripsi                 14502 non-null  str
 8   bahasa                    14502 non-null  str
 9   kategori                  14502 non-null  str
 10  tahun_terbit              14305 non-null  float64
 11  key                       14502 non-null  str
 12  confidence                14257 non-null  float64
 13  volume_info               13681 non-null  str
 14  isbn_10_enrich            12792 non-null  str
 15  isbn_13_enrich            12796 non-null  float64
 16  image_url                 11589 non-null  str
 17  judul_full                14502 non-null  str
 18  book_id                   14502 non-null  str
 19  deskripsi_count           14502 non-null  int64
 20  deskripsi_count_category  14499 non-null  str
dtypes: float64(3), int64(1), str(17)
memory usage: 46.3 MB

In [3]:
books[['book_id','judul_full']].head(5)

   book_id                                         judul_full
0  B000003             Preparing for the Twenty-first Century
1  B000005                        The Illustrator 9 Wow! Book
2  B000006  Crucial Decisions leadership in policymaking a...
3  B000010                                 Basic Biochemistry
4  B000017             Retail Management a strategic approach

In [4]:
# make bookId
books['bookId'] = books.index + 1
books[['book_id', 'bookId','judul_full']].head(10)

   book_id  bookId                                         judul_full
0  B000003       1             Preparing for the Twenty-first Century
1  B000005       2                        The Illustrator 9 Wow! Book
2  B000006       3  Crucial Decisions leadership in policymaking a...
3  B000010       4                                 Basic Biochemistry
4  B000017       5             Retail Management a strategic approach
5  B000019       6  The Capital Budgeting Decision economic analys...
6  B000022       7  Logistical Management a systems integration of...
7  B000025       8                                      Heat Transfer
8  B000027       9                         Principles of Horticulture
9  B000044      10                           Elements of Econometrics

In [5]:
id_to_books = dict(zip(books['bookId'], books['book_id']))
id_to_books[0] = ""

id_to_books

{1: 'B000003',
 2: 'B000005',
 3: 'B000006',
 4: 'B000010',
 5: 'B000017',
 6: 'B000019',
 7: 'B000022',
 8: 'B000025',
 9: 'B000027',
 10: 'B000044',
 11: 'B000045',
 12: 'B000051',
 13: 'B000052',
 14: 'B000057',
 15: 'B000058',
 16: 'B000060',
 17: 'B000061',
 18: 'B000063',
 19: 'B000073',
 20: 'B000079',
 21: 'B000080',
 22: 'B000086',
 23: 'B000087',
 24: 'B000088',
 25: 'B000089',
 26: 'B000090',
 27: 'B000091',
 28: 'B000092',
 29: 'B000094',
 30: 'B000095',
 31: 'B000096',
 32: 'B000097',
 33: 'B000098',
 34: 'B000099',
 35: 'B000100',
 36: 'B000101',
 37: 'B000102',
 38: 'B000113',
 39: 'B000118',
 40: 'B000120',
 41: 'B000123',
 42: 'B000129',
 43: 'B000130',
 44: 'B000134',
 45: 'B000135',
 46: 'B000136',
 47: 'B000137',
 48: 'B000139',
 49: 'B000141',
 50: 'B000144',
 51: 'B000145',
 52: 'B000151',
 53: 'B000154',
 54: 'B000158',
 55: 'B000159',
 56: 'B000161',
 57: 'B000167',
 58: 'B000174',
 59: 'B000179',
 60: 'B000180',
 61: 'B000182',
 62: 'B000185',
 63: 'B000186',
 64: 'B000189',
 65: 'B000196',
 66: 'B000197',
 67: 'B000199',
 68: 'B000201',
 69: 'B000204',
 70: 'B000216',
 71: 'B000217',
 72: 'B000218',
 73: 'B000219',
 74: 'B000220',
 75: 'B000221',
 76: 'B000223',
 77: 'B000226',
 78: 'B000230',
 79: 'B000231',
 80: 'B000232',
 81: 'B000233',
 82: 'B000234',
 83: 'B000235',
 84: 'B000236',
 85: 'B000238',
 86: 'B000246',
 87: 'B000247',
 88: 'B000248',
 89: 'B000249',
 90: 'B000251',
 91: 'B000252',
 92: 'B000253',
 93: 'B000254',
 94: 'B000255',
 95: 'B000256',
 96: 'B000258',
 97: 'B000259',
 98: 'B000263',
 99: 'B000271',
 100: 'B000272',
 101: 'B000275',
 102: 'B000276',
 103: 'B000278',
 104: 'B000280',
 105: 'B000286',
 106: 'B000287',
 107: 'B000288',
 108: 'B000290',
 109: 'B000292',
 110: 'B000295',
 111: 'B000297',
 112: 'B000298',
 113: 'B000299',
 114: 'B000302',
 115: 'B000304',
 116: 'B000306',
 117: 'B000310',
 118: 'B000314',
 119: 'B000316',
 120: 'B000317',
 121: 'B000324',
 122: 'B000326',
 123: 'B000329',
 124: 'B000330',
 125: 'B000331',
 126: 'B000332',
 127: 'B000336',
 128: 'B000339',
 129: 'B000341',
 130: 'B000352',
 131: 'B000353',
 132: 'B000354',
 133: 'B000355',
 134: 'B000356',
 135: 'B000357',
 136: 'B000362',
 137: 'B000371',
 138: 'B000372',
 139: 'B000373',
 140: 'B000375',
 141: 'B000376',
 142: 'B000377',
 143: 'B000382',
 144: 'B000383',
 145: 'B000384',
 146: 'B000387',
 147: 'B000388',
 148: 'B000391',
 149: 'B000396',
 150: 'B000397',
 151: 'B000400',
 152: 'B000401',
 153: 'B000402',
 154: 'B000405',
 155: 'B000406',
 156: 'B000409',
 157: 'B000410',
 158: 'B000413',
 159: 'B000415',
 160: 'B000416',
 161: 'B000417',
 162: 'B000421',
 163: 'B000432',
 164: 'B000435',
 165: 'B000437',
 166: 'B000438',
 167: 'B000444',
 168: 'B000446',
 169: 'B000447',
 170: 'B000449',
 171: 'B000451',
 172: 'B000453',
 173: 'B000456',
 174: 'B000457',
 175: 'B000458',
 176: 'B000461',
 177: 'B000463',
 178: 'B000468',
 179: 'B000469',
 180: 'B000471',
 181: 'B000475',
 182: 'B000478',
 183: 'B000483',
 184: 'B000493',
 185: 'B000496',
 186: 'B000501',
 187: 'B000502',
 188: 'B000503',
 189: 'B000504',
 190: 'B000507',
 191: 'B000510',
 192: 'B000511',
 193: 'B000514',
 194: 'B000515',
 195: 'B000517',
 196: 'B000518',
 197: 'B000520',
 198: 'B000522',
 199: 'B000523',
 200: 'B000526',
 201: 'B000531',
 202: 'B000535',
 203: 'B000538',
 204: 'B000543',
 205: 'B000550',
 206: 'B000551',
 207: 'B000552',
 208: 'B000554',
 209: 'B000555',
 210: 'B000556',
 211: 'B000558',
 212: 'B000564',
 213: 'B000580',
 214: 'B000585',
 215: 'B000592',
 216: 'B000600',
 217: 'B000601',
 218: 'B000602',
 219: 'B000604',
 220: 'B000605',
 221: 'B000606',
 222: 'B000608',
 223: 'B000609',
 224: 'B000614',
 225: 'B000615',
 226: 'B000619',
 227: 'B000622',
 228: 'B000623',
 229: 'B000626',
 230: 'B000627',
 231: 'B000629',
 232: 'B000630',
 233: 'B000631',
 234: 'B000635',
 235: 'B000636',
 236: 'B000637',
 237: 'B000638',
 238: 'B000640',
 239: 'B000643',
 240: 'B000645',
 241: 'B000646',
 242: 'B000647',
 243: 'B000648',
 244: 'B000649',
 245: 'B000650',
 246: 'B000651',
 247: 'B000654',
 248: 'B000655',
 249: 'B000656',
 250: 'B000658',
 251: 'B000659',
 252: 'B000661',
 253: 'B000662',
 254: 'B000663',
 255: 'B000664',
 256: 'B000669',
 257: 'B000670',
 258: 'B000672',
 259: 'B000674',
 260: 'B000675',
 261: 'B000676',
 262: 'B000681',
 263: 'B000682',
 264: 'B000683',
 265: 'B000684',
 266: 'B000685',
 267: 'B000686',
 268: 'B000687',
 269: 'B000688',
 270: 'B000689',
 271: 'B000691',
 272: 'B000693',
 273: 'B000696',
 274: 'B000697',
 275: 'B000698',
 276: 'B000700',
 277: 'B000701',
 278: 'B000702',
 279: 'B000703',
 280: 'B000705',
 281: 'B000706',
 282: 'B000707',
 283: 'B000708',
 284: 'B000709',
 285: 'B000710',
 286: 'B000711',
 287: 'B000712',
 288: 'B000713',
 289: 'B000715',
 290: 'B000717',
 291: 'B000718',
 292: 'B000720',
 293: 'B000721',
 294: 'B000722',
 295: 'B000725',
 296: 'B000726',
 297: 'B000727',
 298: 'B000728',
 299: 'B000729',
 300: 'B000732',
 301: 'B000734',
 302: 'B000735',
 303: 'B000736',
 304: 'B000737',
 305: 'B000738',
 306: 'B000739',
 307: 'B000741',
 308: 'B000744',
 309: 'B000745',
 310: 'B000746',
 311: 'B000747',
 312: 'B000750',
 313: 'B000751',
 314: 'B000752',
 315: 'B000753',
 316: 'B000754',
 317: 'B000755',
 318: 'B000756',
 319: 'B000757',
 320: 'B000758',
 321: 'B000759',
 322: 'B000760',
 323: 'B000762',
 324: 'B000767',
 325: 'B000771',
 326: 'B000772',
 327: 'B000773',
 328: 'B000774',
 329: 'B000775',
 330: 'B000776',
 331: 'B000779',
 332: 'B000780',
 333: 'B000781',
 334: 'B000783',
 335: 'B000790',
 336: 'B000796',
 337: 'B000798',
 338: 'B000806',
 339: 'B000807',
 340: 'B000812',
 341: 'B000814',
 342: 'B000815',
 343: 'B000816',
 344: 'B000817',
 345: 'B000821',
 346: 'B000822',
 347: 'B000824',
 348: 'B000834',
 349: 'B000836',
 350: 'B000840',
 351: 'B000842',
 352: 'B000843',
 353: 'B000844',
 354: 'B000851',
 355: 'B000861',
 356: 'B000862',
 357: 'B000867',
 358: 'B000868',
 359: 'B000869',
 360: 'B000870',
 361: 'B000873',
 362: 'B000874',
 363: 'B000875',
 364: 'B000876',
 365: 'B000877',
 366: 'B000878',
 367: 'B000882',
 368: 'B000883',
 369: 'B000885',
 370: 'B000886',
 371: 'B000888',
 372: 'B000890',
 373: 'B000891',
 374: 'B000892',
 375: 'B000893',
 376: 'B000894',
 377: 'B000895',
 378: 'B000897',
 379: 'B000898',
 380: 'B000899',
 381: 'B000901',
 382: 'B000905',
 383: 'B000906',
 384: 'B000907',
 385: 'B000908',
 386: 'B000909',
 387: 'B000910',
 388: 'B000911',
 389: 'B000912',
 390: 'B000913',
 391: 'B000914',
 392: 'B000915',
 393: 'B000916',
 394: 'B000918',
 395: 'B000919',
 396: 'B000920',
 397: 'B000928',
 398: 'B000929',
 399: 'B000931',
 400: 'B000932',
 401: 'B000933',
 402: 'B000934',
 403: 'B000936',
 404: 'B000937',
 405: 'B000939',
 406: 'B000941',
 407: 'B000943',
 408: 'B000945',
 409: 'B000946',
 410: 'B000948',
 411: 'B000949',
 412: 'B000952',
 413: 'B000953',
 414: 'B000954',
 415: 'B000956',
 416: 'B000957',
 417: 'B000960',
 418: 'B000961',
 419: 'B000962',
 420: 'B000964',
 421: 'B000966',
 422: 'B000968',
 423: 'B000970',
 424: 'B000971',
 425: 'B000973',
 426: 'B000974',
 427: 'B000975',
 428: 'B000980',
 429: 'B000981',
 430: 'B000982',
 431: 'B000983',
 432: 'B000984',
 433: 'B000985',
 434: 'B000986',
 435: 'B000987',
 436: 'B000988',
 437: 'B000989',
 438: 'B000990',
 439: 'B000991',
 440: 'B000992',
 441: 'B000996',
 442: 'B000997',
 443: 'B000998',
 444: 'B000999',
 445: 'B001002',
 446: 'B001003',
 447: 'B001004',
 448: 'B001005',
 449: 'B001007',
 450: 'B001009',
 451: 'B001011',
 452: 'B001012',
 453: 'B001015',
 454: 'B001016',
 455: 'B001018',
 456: 'B001019',
 457: 'B001023',
 458: 'B001024',
 459: 'B001025',
 460: 'B001026',
 461: 'B001029',
 462: 'B001031',
 463: 'B001032',
 464: 'B001033',
 465: 'B001034',
 466: 'B001035',
 467: 'B001036',
 468: 'B001037',
 469: 'B001038',
 470: 'B001039',
 471: 'B001040',
 472: 'B001041',
 473: 'B001045',
 474: 'B001046',
 475: 'B001048',
 476: 'B001049',
 477: 'B001050',
 478: 'B001056',
 479: 'B001058',
 480: 'B001059',
 481: 'B001060',
 482: 'B001061',
 483: 'B001063',
 484: 'B001067',
 485: 'B001069',
 486: 'B001070',
 487: 'B001072',
 488: 'B001074',
 489: 'B001079',
 490: 'B001080',
 491: 'B001081',
 492: 'B001082',
 493: 'B001083',
 494: 'B001084',
 495: 'B001086',
 496: 'B001087',
 497: 'B001091',
 498: 'B001092',
 499: 'B001094',
 500: 'B001095',
 501: 'B001096',
 502: 'B001097',
 503: 'B001099',
 504: 'B001100',
 505: 'B001102',
 506: 'B001108',
 507: 'B001109',
 508: 'B001113',
 509: 'B001118',
 510: 'B001121',
 511: 'B001122',
 512: 'B001123',
 513: 'B001124',
 514: 'B001126',
 515: 'B001127',
 516: 'B001128',
 517: 'B001129',
 518: 'B001131',
 519: 'B001132',
 520: 'B001134',
 521: 'B001136',
 522: 'B001138',
 523: 'B001141',
 524: 'B001142',
 525: 'B001143',
 526: 'B001145',
 527: 'B001148',
 528: 'B001150',
 529: 'B001151',
 530: 'B001152',
 531: 'B001154',
 532: 'B001155',
 533: 'B001156',
 534: 'B001157',
 535: 'B001162',
 536: 'B001168',
 537: 'B001169',
 538: 'B001170',
 539: 'B001173',
 540: 'B001174',
 541: 'B001175',
 542: 'B001176',
 543: 'B001177',
 544: 'B001179',
 545: 'B001181',
 546: 'B001182',
 547: 'B001184',
 548: 'B001185',
 549: 'B001189',
 550: 'B001194',
 551: 'B001196',
 552: 'B001198',
 553: 'B001199',
 554: 'B001200',
 555: 'B001201',
 556: 'B001202',
 557: 'B001205',
 558: 'B001212',
 559: 'B001215',
 560: 'B001216',
 561: 'B001217',
 562: 'B001218',
 563: 'B001219',
 564: 'B001220',
 565: 'B001221',
 566: 'B001223',
 567: 'B001226',
 568: 'B001227',
 569: 'B001229',
 570: 'B001230',
 571: 'B001232',
 572: 'B001234',
 573: 'B001240',
 574: 'B001254',
 575: 'B001263',
 576: 'B001270',
 577: 'B001272',
 578: 'B001273',
 579: 'B001274',
 580: 'B001275',
 581: 'B001276',
 582: 'B001277',
 583: 'B001279',
 584: 'B001280',
 585: 'B001283',
 586: 'B001285',
 587: 'B001286',
 588: 'B001287',
 589: 'B001288',
 590: 'B001289',
 591: 'B001290',
 592: 'B001291',
 593: 'B001294',
 594: 'B001296',
 595: 'B001298',
 596: 'B001299',
 597: 'B001300',
 598: 'B001301',
 599: 'B001302',
 600: 'B001305',
 601: 'B001306',
 602: 'B001309',
 603: 'B001320',
 604: 'B001330',
 605: 'B001358',
 606: 'B001360',
 607: 'B001361',
 608: 'B001362',
 609: 'B001363',
 610: 'B001364',
 611: 'B001365',
 612: 'B001366',
 613: 'B001368',
 614: 'B001369',
 615: 'B001370',
 616: 'B001375',
 617: 'B001378',
 618: 'B001387',
 619: 'B001391',
 620: 'B001393',
 621: 'B001394',
 622: 'B001395',
 623: 'B001396',
 624: 'B001397',
 625: 'B001398',
 626: 'B001399',
 627: 'B001400',
 628: 'B001401',
 629: 'B001403',
 630: 'B001404',
 631: 'B001405',
 632: 'B001418',
 633: 'B001421',
 634: 'B001422',
 635: 'B001424',
 636: 'B001425',
 637: 'B001426',
 638: 'B001427',
 639: 'B001428',
 640: 'B001429',
 641: 'B001433',
 642: 'B001434',
 643: 'B001435',
 644: 'B001436',
 645: 'B001439',
 646: 'B001442',
 647: 'B001448',
 648: 'B001460',
 649: 'B001461',
 650: 'B001467',
 651: 'B001471',
 652: 'B001480',
 653: 'B001535',
 654: 'B001542',
 655: 'B001550',
 656: 'B001551',
 657: 'B001553',
 658: 'B001555',
 659: 'B001556',
 660: 'B001557',
 661: 'B001558',
 662: 'B001560',
 663: 'B001561',
 664: 'B001562',
 665: 'B001566',
 666: 'B001567',
 667: 'B001568',
 668: 'B001570',
 669: 'B001571',
 670: 'B001573',
 671: 'B001574',
 672: 'B001575',
 673: 'B001576',
 674: 'B001577',
 675: 'B001584',
 676: 'B001586',
 677: 'B001587',
 678: 'B001588',
 679: 'B001589',
 680: 'B001590',
 681: 'B001591',
 682: 'B001595',
 683: 'B001600',
 684: 'B001602',
 685: 'B001606',
 686: 'B001609',
 687: 'B001610',
 688: 'B001614',
 689: 'B001616',
 690: 'B001617',
 691: 'B001618',
 692: 'B001619',
 693: 'B001620',
 694: 'B001621',
 695: 'B001622',
 696: 'B001623',
 697: 'B001624',
 698: 'B001625',
 699: 'B001626',
 700: 'B001627',
 701: 'B001629',
 702: 'B001630',
 703: 'B001631',
 704: 'B001632',
 705: 'B001633',
 706: 'B001634',
 707: 'B001635',
 708: 'B001636',
 709: 'B001637',
 710: 'B001638',
 711: 'B001639',
 712: 'B001640',
 713: 'B001641',
 714: 'B001644',
 715: 'B001645',
 716: 'B001647',
 717: 'B001648',
 718: 'B001649',
 719: 'B001650',
 720: 'B001653',
 721: 'B001659',
 722: 'B001661',
 723: 'B001662',
 724: 'B001664',
 725: 'B001666',
 726: 'B001667',
 727: 'B001668',
 728: 'B001669',
 729: 'B001670',
 730: 'B001671',
 731: 'B001672',
 732: 'B001675',
 733: 'B001681',
 734: 'B001682',
 735: 'B001683',
 736: 'B001687',
 737: 'B001688',
 738: 'B001689',
 739: 'B001692',
 740: 'B001693',
 741: 'B001694',
 742: 'B001698',
 743: 'B001700',
 744: 'B001714',
 745: 'B001731',
 746: 'B001738',
 747: 'B001747',
 748: 'B001748',
 749: 'B001749',
 750: 'B001755',
 751: 'B001756',
 752: 'B001757',
 753: 'B001759',
 754: 'B001760',
 755: 'B001761',
 756: 'B001769',
 757: 'B001770',
 758: 'B001771',
 759: 'B001772',
 760: 'B001774',
 761: 'B001779',
 762: 'B001781',
 763: 'B001782',
 764: 'B001783',
 765: 'B001784',
 766: 'B001786',
 767: 'B001787',
 768: 'B001788',
 769: 'B001789',
 770: 'B001790',
 771: 'B001792',
 772: 'B001793',
 773: 'B001799',
 774: 'B001802',
 775: 'B001805',
 776: 'B001810',
 777: 'B001822',
 778: 'B001823',
 779: 'B001830',
 780: 'B001836',
 781: 'B001838',
 782: 'B001841',
 783: 'B001845',
 784: 'B001846',
 785: 'B001847',
 786: 'B001850',
 787: 'B001851',
 788: 'B001852',
 789: 'B001853',
 790: 'B001858',
 791: 'B001859',
 792: 'B001862',
 793: 'B001863',
 794: 'B001867',
 795: 'B001869',
 796: 'B001870',
 797: 'B001871',
 798: 'B001873',
 799: 'B001874',
 800: 'B001875',
 801: 'B001878',
 802: 'B001879',
 803: 'B001880',
 804: 'B001881',
 805: 'B001883',
 806: 'B001884',
 807: 'B001885',
 808: 'B001887',
 809: 'B001889',
 810: 'B001890',
 811: 'B001891',
 812: 'B001893',
 813: 'B001901',
 814: 'B001902',
 815: 'B001903',
 816: 'B001905',
 817: 'B001911',
 818: 'B001913',
 819: 'B001914',
 820: 'B001922',
 821: 'B001925',
 822: 'B001927',
 823: 'B001928',
 824: 'B001931',
 825: 'B001932',
 826: 'B001934',
 827: 'B001938',
 828: 'B001939',
 829: 'B001940',
 830: 'B001941',
 831: 'B001942',
 832: 'B001944',
 833: 'B001945',
 834: 'B001946',
 835: 'B001949',
 836: 'B001950',
 837: 'B001951',
 838: 'B001952',
 839: 'B001953',
 840: 'B001954',
 841: 'B001955',
 842: 'B001957',
 843: 'B001959',
 844: 'B001964',
 845: 'B001965',
 846: 'B001968',
 847: 'B001969',
 848: 'B001971',
 849: 'B001972',
 850: 'B001973',
 851: 'B001974',
 852: 'B001975',
 853: 'B001976',
 854: 'B001978',
 855: 'B001979',
 856: 'B001980',
 857: 'B001981',
 858: 'B001982',
 859: 'B001983',
 860: 'B001984',
 861: 'B001985',
 862: 'B001986',
 863: 'B001987',
 864: 'B001991',
 865: 'B001992',
 866: 'B001993',
 867: 'B001994',
 868: 'B001995',
 869: 'B001996',
 870: 'B001997',
 871: 'B001999',
 872: 'B002000',
 873: 'B002002',
 874: 'B002006',
 875: 'B002007',
 876: 'B002008',
 877: 'B002009',
 878: 'B002010',
 879: 'B002011',
 880: 'B002012',
 881: 'B002013',
 882: 'B002014',
 883: 'B002015',
 884: 'B002016',
 885: 'B002019',
 886: 'B002024',
 887: 'B002026',
 888: 'B002031',
 889: 'B002032',
 890: 'B002033',
 891: 'B002038',
 892: 'B002039',
 893: 'B002041',
 894: 'B002042',
 895: 'B002043',
 896: 'B002044',
 897: 'B002045',
 898: 'B002046',
 899: 'B002049',
 900: 'B002050',
 901: 'B002051',
 902: 'B002052',
 903: 'B002053',
 904: 'B002054',
 905: 'B002055',
 906: 'B002056',
 907: 'B002057',
 908: 'B002058',
 909: 'B002060',
 910: 'B002061',
 911: 'B002062',
 912: 'B002063',
 913: 'B002065',
 914: 'B002066',
 915: 'B002067',
 916: 'B002068',
 917: 'B002071',
 918: 'B002072',
 919: 'B002073',
 920: 'B002074',
 921: 'B002075',
 922: 'B002076',
 923: 'B002077',
 924: 'B002079',
 925: 'B002080',
 926: 'B002082',
 927: 'B002083',
 928: 'B002084',
 929: 'B002086',
 930: 'B002091',
 931: 'B002092',
 932: 'B002093',
 933: 'B002094',
 934: 'B002095',
 935: 'B002096',
 936: 'B002098',
 937: 'B002102',
 938: 'B002103',
 939: 'B002104',
 940: 'B002105',
 941: 'B002107',
 942: 'B002108',
 943: 'B002109',
 944: 'B002110',
 945: 'B002114',
 946: 'B002115',
 947: 'B002116',
 948: 'B002117',
 949: 'B002121',
 950: 'B002123',
 951: 'B002125',
 952: 'B002126',
 953: 'B002127',
 954: 'B002128',
 955: 'B002129',
 956: 'B002130',
 957: 'B002132',
 958: 'B002133',
 959: 'B002134',
 960: 'B002135',
 961: 'B002139',
 962: 'B002140',
 963: 'B002141',
 964: 'B002144',
 965: 'B002146',
 966: 'B002147',
 967: 'B002148',
 968: 'B002149',
 969: 'B002150',
 970: 'B002151',
 971: 'B002152',
 972: 'B002153',
 973: 'B002163',
 974: 'B002164',
 975: 'B002165',
 976: 'B002169',
 977: 'B002170',
 978: 'B002172',
 979: 'B002173',
 980: 'B002174',
 981: 'B002176',
 982: 'B002177',
 983: 'B002179',
 984: 'B002180',
 985: 'B002181',
 986: 'B002182',
 987: 'B002183',
 988: 'B002184',
 989: 'B002185',
 990: 'B002188',
 991: 'B002226',
 992: 'B002232',
 993: 'B002234',
 994: 'B002235',
 995: 'B002236',
 996: 'B002238',
 997: 'B002239',
 998: 'B002244',
 999: 'B002249',
 1000: 'B002256',
 ...}

In [6]:
books_to_id = dict(zip(books['book_id'], books['bookId']))
books_to_id[''] = 0
books_to_id

{'B000003': 1,
 'B000005': 2,
 'B000006': 3,
 'B000010': 4,
 'B000017': 5,
 'B000019': 6,
 'B000022': 7,
 'B000025': 8,
 'B000027': 9,
 'B000044': 10,
 'B000045': 11,
 'B000051': 12,
 'B000052': 13,
 'B000057': 14,
 'B000058': 15,
 'B000060': 16,
 'B000061': 17,
 'B000063': 18,
 'B000073': 19,
 'B000079': 20,
 'B000080': 21,
 'B000086': 22,
 'B000087': 23,
 'B000088': 24,
 'B000089': 25,
 'B000090': 26,
 'B000091': 27,
 'B000092': 28,
 'B000094': 29,
 'B000095': 30,
 'B000096': 31,
 'B000097': 32,
 'B000098': 33,
 'B000099': 34,
 'B000100': 35,
 'B000101': 36,
 'B000102': 37,
 'B000113': 38,
 'B000118': 39,
 'B000120': 40,
 'B000123': 41,
 'B000129': 42,
 'B000130': 43,
 'B000134': 44,
 'B000135': 45,
 'B000136': 46,
 'B000137': 47,
 'B000139': 48,
 'B000141': 49,
 'B000144': 50,
 'B000145': 51,
 'B000151': 52,
 'B000154': 53,
 'B000158': 54,
 'B000159': 55,
 'B000161': 56,
 'B000167': 57,
 'B000174': 58,
 'B000179': 59,
 'B000180': 60,
 'B000182': 61,
 'B000185': 62,
 'B000186': 63,
 'B000189': 64,
 'B000196': 65,
 'B000197': 66,
 'B000199': 67,
 'B000201': 68,
 'B000204': 69,
 'B000216': 70,
 'B000217': 71,
 'B000218': 72,
 'B000219': 73,
 'B000220': 74,
 'B000221': 75,
 'B000223': 76,
 'B000226': 77,
 'B000230': 78,
 'B000231': 79,
 'B000232': 80,
 'B000233': 81,
 'B000234': 82,
 'B000235': 83,
 'B000236': 84,
 'B000238': 85,
 'B000246': 86,
 'B000247': 87,
 'B000248': 88,
 'B000249': 89,
 'B000251': 90,
 'B000252': 91,
 'B000253': 92,
 'B000254': 93,
 'B000255': 94,
 'B000256': 95,
 'B000258': 96,
 'B000259': 97,
 'B000263': 98,
 'B000271': 99,
 'B000272': 100,
 'B000275': 101,
 'B000276': 102,
 'B000278': 103,
 'B000280': 104,
 'B000286': 105,
 'B000287': 106,
 'B000288': 107,
 'B000290': 108,
 'B000292': 109,
 'B000295': 110,
 'B000297': 111,
 'B000298': 112,
 'B000299': 113,
 'B000302': 114,
 'B000304': 115,
 'B000306': 116,
 'B000310': 117,
 'B000314': 118,
 'B000316': 119,
 'B000317': 120,
 'B000324': 121,
 'B000326': 122,
 'B000329': 123,
 'B000330': 124,
 'B000331': 125,
 'B000332': 126,
 'B000336': 127,
 'B000339': 128,
 'B000341': 129,
 'B000352': 130,
 'B000353': 131,
 'B000354': 132,
 'B000355': 133,
 'B000356': 134,
 'B000357': 135,
 'B000362': 136,
 'B000371': 137,
 'B000372': 138,
 'B000373': 139,
 'B000375': 140,
 'B000376': 141,
 'B000377': 142,
 'B000382': 143,
 'B000383': 144,
 'B000384': 145,
 'B000387': 146,
 'B000388': 147,
 'B000391': 148,
 'B000396': 149,
 'B000397': 150,
 'B000400': 151,
 'B000401': 152,
 'B000402': 153,
 'B000405': 154,
 'B000406': 155,
 'B000409': 156,
 'B000410': 157,
 'B000413': 158,
 'B000415': 159,
 'B000416': 160,
 'B000417': 161,
 'B000421': 162,
 'B000432': 163,
 'B000435': 164,
 'B000437': 165,
 'B000438': 166,
 'B000444': 167,
 'B000446': 168,
 'B000447': 169,
 'B000449': 170,
 'B000451': 171,
 'B000453': 172,
 'B000456': 173,
 'B000457': 174,
 'B000458': 175,
 'B000461': 176,
 'B000463': 177,
 'B000468': 178,
 'B000469': 179,
 'B000471': 180,
 'B000475': 181,
 'B000478': 182,
 'B000483': 183,
 'B000493': 184,
 'B000496': 185,
 'B000501': 186,
 'B000502': 187,
 'B000503': 188,
 'B000504': 189,
 'B000507': 190,
 'B000510': 191,
 'B000511': 192,
 'B000514': 193,
 'B000515': 194,
 'B000517': 195,
 'B000518': 196,
 'B000520': 197,
 'B000522': 198,
 'B000523': 199,
 'B000526': 200,
 'B000531': 201,
 'B000535': 202,
 'B000538': 203,
 'B000543': 204,
 'B000550': 205,
 'B000551': 206,
 'B000552': 207,
 'B000554': 208,
 'B000555': 209,
 'B000556': 210,
 'B000558': 211,
 'B000564': 212,
 'B000580': 213,
 'B000585': 214,
 'B000592': 215,
 'B000600': 216,
 'B000601': 217,
 'B000602': 218,
 'B000604': 219,
 'B000605': 220,
 'B000606': 221,
 'B000608': 222,
 'B000609': 223,
 'B000614': 224,
 'B000615': 225,
 'B000619': 226,
 'B000622': 227,
 'B000623': 228,
 'B000626': 229,
 'B000627': 230,
 'B000629': 231,
 'B000630': 232,
 'B000631': 233,
 'B000635': 234,
 'B000636': 235,
 'B000637': 236,
 'B000638': 237,
 'B000640': 238,
 'B000643': 239,
 'B000645': 240,
 'B000646': 241,
 'B000647': 242,
 'B000648': 243,
 'B000649': 244,
 'B000650': 245,
 'B000651': 246,
 'B000654': 247,
 'B000655': 248,
 'B000656': 249,
 'B000658': 250,
 'B000659': 251,
 'B000661': 252,
 'B000662': 253,
 'B000663': 254,
 'B000664': 255,
 'B000669': 256,
 'B000670': 257,
 'B000672': 258,
 'B000674': 259,
 'B000675': 260,
 'B000676': 261,
 'B000681': 262,
 'B000682': 263,
 'B000683': 264,
 'B000684': 265,
 'B000685': 266,
 'B000686': 267,
 'B000687': 268,
 'B000688': 269,
 'B000689': 270,
 'B000691': 271,
 'B000693': 272,
 'B000696': 273,
 'B000697': 274,
 'B000698': 275,
 'B000700': 276,
 'B000701': 277,
 'B000702': 278,
 'B000703': 279,
 'B000705': 280,
 'B000706': 281,
 'B000707': 282,
 'B000708': 283,
 'B000709': 284,
 'B000710': 285,
 'B000711': 286,
 'B000712': 287,
 'B000713': 288,
 'B000715': 289,
 'B000717': 290,
 'B000718': 291,
 'B000720': 292,
 'B000721': 293,
 'B000722': 294,
 'B000725': 295,
 'B000726': 296,
 'B000727': 297,
 'B000728': 298,
 'B000729': 299,
 'B000732': 300,
 'B000734': 301,
 'B000735': 302,
 'B000736': 303,
 'B000737': 304,
 'B000738': 305,
 'B000739': 306,
 'B000741': 307,
 'B000744': 308,
 'B000745': 309,
 'B000746': 310,
 'B000747': 311,
 'B000750': 312,
 'B000751': 313,
 'B000752': 314,
 'B000753': 315,
 'B000754': 316,
 'B000755': 317,
 'B000756': 318,
 'B000757': 319,
 'B000758': 320,
 'B000759': 321,
 'B000760': 322,
 'B000762': 323,
 'B000767': 324,
 'B000771': 325,
 'B000772': 326,
 'B000773': 327,
 'B000774': 328,
 'B000775': 329,
 'B000776': 330,
 'B000779': 331,
 'B000780': 332,
 'B000781': 333,
 'B000783': 334,
 'B000790': 335,
 'B000796': 336,
 'B000798': 337,
 'B000806': 338,
 'B000807': 339,
 'B000812': 340,
 'B000814': 341,
 'B000815': 342,
 'B000816': 343,
 'B000817': 344,
 'B000821': 345,
 'B000822': 346,
 'B000824': 347,
 'B000834': 348,
 'B000836': 349,
 'B000840': 350,
 'B000842': 351,
 'B000843': 352,
 'B000844': 353,
 'B000851': 354,
 'B000861': 355,
 'B000862': 356,
 'B000867': 357,
 'B000868': 358,
 'B000869': 359,
 'B000870': 360,
 'B000873': 361,
 'B000874': 362,
 'B000875': 363,
 'B000876': 364,
 'B000877': 365,
 'B000878': 366,
 'B000882': 367,
 'B000883': 368,
 'B000885': 369,
 'B000886': 370,
 'B000888': 371,
 'B000890': 372,
 'B000891': 373,
 'B000892': 374,
 'B000893': 375,
 'B000894': 376,
 'B000895': 377,
 'B000897': 378,
 'B000898': 379,
 'B000899': 380,
 'B000901': 381,
 'B000905': 382,
 'B000906': 383,
 'B000907': 384,
 'B000908': 385,
 'B000909': 386,
 'B000910': 387,
 'B000911': 388,
 'B000912': 389,
 'B000913': 390,
 'B000914': 391,
 'B000915': 392,
 'B000916': 393,
 'B000918': 394,
 'B000919': 395,
 'B000920': 396,
 'B000928': 397,
 'B000929': 398,
 'B000931': 399,
 'B000932': 400,
 'B000933': 401,
 'B000934': 402,
 'B000936': 403,
 'B000937': 404,
 'B000939': 405,
 'B000941': 406,
 'B000943': 407,
 'B000945': 408,
 'B000946': 409,
 'B000948': 410,
 'B000949': 411,
 'B000952': 412,
 'B000953': 413,
 'B000954': 414,
 'B000956': 415,
 'B000957': 416,
 'B000960': 417,
 'B000961': 418,
 'B000962': 419,
 'B000964': 420,
 'B000966': 421,
 'B000968': 422,
 'B000970': 423,
 'B000971': 424,
 'B000973': 425,
 'B000974': 426,
 'B000975': 427,
 'B000980': 428,
 'B000981': 429,
 'B000982': 430,
 'B000983': 431,
 'B000984': 432,
 'B000985': 433,
 'B000986': 434,
 'B000987': 435,
 'B000988': 436,
 'B000989': 437,
 'B000990': 438,
 'B000991': 439,
 'B000992': 440,
 'B000996': 441,
 'B000997': 442,
 'B000998': 443,
 'B000999': 444,
 'B001002': 445,
 'B001003': 446,
 'B001004': 447,
 'B001005': 448,
 'B001007': 449,
 'B001009': 450,
 'B001011': 451,
 'B001012': 452,
 'B001015': 453,
 'B001016': 454,
 'B001018': 455,
 'B001019': 456,
 'B001023': 457,
 'B001024': 458,
 'B001025': 459,
 'B001026': 460,
 'B001029': 461,
 'B001031': 462,
 'B001032': 463,
 'B001033': 464,
 'B001034': 465,
 'B001035': 466,
 'B001036': 467,
 'B001037': 468,
 'B001038': 469,
 'B001039': 470,
 'B001040': 471,
 'B001041': 472,
 'B001045': 473,
 'B001046': 474,
 'B001048': 475,
 'B001049': 476,
 'B001050': 477,
 'B001056': 478,
 'B001058': 479,
 'B001059': 480,
 'B001060': 481,
 'B001061': 482,
 'B001063': 483,
 'B001067': 484,
 'B001069': 485,
 'B001070': 486,
 'B001072': 487,
 'B001074': 488,
 'B001079': 489,
 'B001080': 490,
 'B001081': 491,
 'B001082': 492,
 'B001083': 493,
 'B001084': 494,
 'B001086': 495,
 'B001087': 496,
 'B001091': 497,
 'B001092': 498,
 'B001094': 499,
 'B001095': 500,
 'B001096': 501,
 'B001097': 502,
 'B001099': 503,
 'B001100': 504,
 'B001102': 505,
 'B001108': 506,
 'B001109': 507,
 'B001113': 508,
 'B001118': 509,
 'B001121': 510,
 'B001122': 511,
 'B001123': 512,
 'B001124': 513,
 'B001126': 514,
 'B001127': 515,
 'B001128': 516,
 'B001129': 517,
 'B001131': 518,
 'B001132': 519,
 'B001134': 520,
 'B001136': 521,
 'B001138': 522,
 'B001141': 523,
 'B001142': 524,
 'B001143': 525,
 'B001145': 526,
 'B001148': 527,
 'B001150': 528,
 'B001151': 529,
 'B001152': 530,
 'B001154': 531,
 'B001155': 532,
 'B001156': 533,
 'B001157': 534,
 'B001162': 535,
 'B001168': 536,
 'B001169': 537,
 'B001170': 538,
 'B001173': 539,
 'B001174': 540,
 'B001175': 541,
 'B001176': 542,
 'B001177': 543,
 'B001179': 544,
 'B001181': 545,
 'B001182': 546,
 'B001184': 547,
 'B001185': 548,
 'B001189': 549,
 'B001194': 550,
 'B001196': 551,
 'B001198': 552,
 'B001199': 553,
 'B001200': 554,
 'B001201': 555,
 'B001202': 556,
 'B001205': 557,
 'B001212': 558,
 'B001215': 559,
 'B001216': 560,
 'B001217': 561,
 'B001218': 562,
 'B001219': 563,
 'B001220': 564,
 'B001221': 565,
 'B001223': 566,
 'B001226': 567,
 'B001227': 568,
 'B001229': 569,
 'B001230': 570,
 'B001232': 571,
 'B001234': 572,
 'B001240': 573,
 'B001254': 574,
 'B001263': 575,
 'B001270': 576,
 'B001272': 577,
 'B001273': 578,
 'B001274': 579,
 'B001275': 580,
 'B001276': 581,
 'B001277': 582,
 'B001279': 583,
 'B001280': 584,
 'B001283': 585,
 'B001285': 586,
 'B001286': 587,
 'B001287': 588,
 'B001288': 589,
 'B001289': 590,
 'B001290': 591,
 'B001291': 592,
 'B001294': 593,
 'B001296': 594,
 'B001298': 595,
 'B001299': 596,
 'B001300': 597,
 'B001301': 598,
 'B001302': 599,
 'B001305': 600,
 'B001306': 601,
 'B001309': 602,
 'B001320': 603,
 'B001330': 604,
 'B001358': 605,
 'B001360': 606,
 'B001361': 607,
 'B001362': 608,
 'B001363': 609,
 'B001364': 610,
 'B001365': 611,
 'B001366': 612,
 'B001368': 613,
 'B001369': 614,
 'B001370': 615,
 'B001375': 616,
 'B001378': 617,
 'B001387': 618,
 'B001391': 619,
 'B001393': 620,
 'B001394': 621,
 'B001395': 622,
 'B001396': 623,
 'B001397': 624,
 'B001398': 625,
 'B001399': 626,
 'B001400': 627,
 'B001401': 628,
 'B001403': 629,
 'B001404': 630,
 'B001405': 631,
 'B001418': 632,
 'B001421': 633,
 'B001422': 634,
 'B001424': 635,
 'B001425': 636,
 'B001426': 637,
 'B001427': 638,
 'B001428': 639,
 'B001429': 640,
 'B001433': 641,
 'B001434': 642,
 'B001435': 643,
 'B001436': 644,
 'B001439': 645,
 'B001442': 646,
 'B001448': 647,
 'B001460': 648,
 'B001461': 649,
 'B001467': 650,
 'B001471': 651,
 'B001480': 652,
 'B001535': 653,
 'B001542': 654,
 'B001550': 655,
 'B001551': 656,
 'B001553': 657,
 'B001555': 658,
 'B001556': 659,
 'B001557': 660,
 'B001558': 661,
 'B001560': 662,
 'B001561': 663,
 'B001562': 664,
 'B001566': 665,
 'B001567': 666,
 'B001568': 667,
 'B001570': 668,
 'B001571': 669,
 'B001573': 670,
 'B001574': 671,
 'B001575': 672,
 'B001576': 673,
 'B001577': 674,
 'B001584': 675,
 'B001586': 676,
 'B001587': 677,
 'B001588': 678,
 'B001589': 679,
 'B001590': 680,
 'B001591': 681,
 'B001595': 682,
 'B001600': 683,
 'B001602': 684,
 'B001606': 685,
 'B001609': 686,
 'B001610': 687,
 'B001614': 688,
 'B001616': 689,
 'B001617': 690,
 'B001618': 691,
 'B001619': 692,
 'B001620': 693,
 'B001621': 694,
 'B001622': 695,
 'B001623': 696,
 'B001624': 697,
 'B001625': 698,
 'B001626': 699,
 'B001627': 700,
 'B001629': 701,
 'B001630': 702,
 'B001631': 703,
 'B001632': 704,
 'B001633': 705,
 'B001634': 706,
 'B001635': 707,
 'B001636': 708,
 'B001637': 709,
 'B001638': 710,
 'B001639': 711,
 'B001640': 712,
 'B001641': 713,
 'B001644': 714,
 'B001645': 715,
 'B001647': 716,
 'B001648': 717,
 'B001649': 718,
 'B001650': 719,
 'B001653': 720,
 'B001659': 721,
 'B001661': 722,
 'B001662': 723,
 'B001664': 724,
 'B001666': 725,
 'B001667': 726,
 'B001668': 727,
 'B001669': 728,
 'B001670': 729,
 'B001671': 730,
 'B001672': 731,
 'B001675': 732,
 'B001681': 733,
 'B001682': 734,
 'B001683': 735,
 'B001687': 736,
 'B001688': 737,
 'B001689': 738,
 'B001692': 739,
 'B001693': 740,
 'B001694': 741,
 'B001698': 742,
 'B001700': 743,
 'B001714': 744,
 'B001731': 745,
 'B001738': 746,
 'B001747': 747,
 'B001748': 748,
 'B001749': 749,
 'B001755': 750,
 'B001756': 751,
 'B001757': 752,
 'B001759': 753,
 'B001760': 754,
 'B001761': 755,
 'B001769': 756,
 'B001770': 757,
 'B001771': 758,
 'B001772': 759,
 'B001774': 760,
 'B001779': 761,
 'B001781': 762,
 'B001782': 763,
 'B001783': 764,
 'B001784': 765,
 'B001786': 766,
 'B001787': 767,
 'B001788': 768,
 'B001789': 769,
 'B001790': 770,
 'B001792': 771,
 'B001793': 772,
 'B001799': 773,
 'B001802': 774,
 'B001805': 775,
 'B001810': 776,
 'B001822': 777,
 'B001823': 778,
 'B001830': 779,
 'B001836': 780,
 'B001838': 781,
 'B001841': 782,
 'B001845': 783,
 'B001846': 784,
 'B001847': 785,
 'B001850': 786,
 'B001851': 787,
 'B001852': 788,
 'B001853': 789,
 'B001858': 790,
 'B001859': 791,
 'B001862': 792,
 'B001863': 793,
 'B001867': 794,
 'B001869': 795,
 'B001870': 796,
 'B001871': 797,
 'B001873': 798,
 'B001874': 799,
 'B001875': 800,
 'B001878': 801,
 'B001879': 802,
 'B001880': 803,
 'B001881': 804,
 'B001883': 805,
 'B001884': 806,
 'B001885': 807,
 'B001887': 808,
 'B001889': 809,
 'B001890': 810,
 'B001891': 811,
 'B001893': 812,
 'B001901': 813,
 'B001902': 814,
 'B001903': 815,
 'B001905': 816,
 'B001911': 817,
 'B001913': 818,
 'B001914': 819,
 'B001922': 820,
 'B001925': 821,
 'B001927': 822,
 'B001928': 823,
 'B001931': 824,
 'B001932': 825,
 'B001934': 826,
 'B001938': 827,
 'B001939': 828,
 'B001940': 829,
 'B001941': 830,
 'B001942': 831,
 'B001944': 832,
 'B001945': 833,
 'B001946': 834,
 'B001949': 835,
 'B001950': 836,
 'B001951': 837,
 'B001952': 838,
 'B001953': 839,
 'B001954': 840,
 'B001955': 841,
 'B001957': 842,
 'B001959': 843,
 'B001964': 844,
 'B001965': 845,
 'B001968': 846,
 'B001969': 847,
 'B001971': 848,
 'B001972': 849,
 'B001973': 850,
 'B001974': 851,
 'B001975': 852,
 'B001976': 853,
 'B001978': 854,
 'B001979': 855,
 'B001980': 856,
 'B001981': 857,
 'B001982': 858,
 'B001983': 859,
 'B001984': 860,
 'B001985': 861,
 'B001986': 862,
 'B001987': 863,
 'B001991': 864,
 'B001992': 865,
 'B001993': 866,
 'B001994': 867,
 'B001995': 868,
 'B001996': 869,
 'B001997': 870,
 'B001999': 871,
 'B002000': 872,
 'B002002': 873,
 'B002006': 874,
 'B002007': 875,
 'B002008': 876,
 'B002009': 877,
 'B002010': 878,
 'B002011': 879,
 'B002012': 880,
 'B002013': 881,
 'B002014': 882,
 'B002015': 883,
 'B002016': 884,
 'B002019': 885,
 'B002024': 886,
 'B002026': 887,
 'B002031': 888,
 'B002032': 889,
 'B002033': 890,
 'B002038': 891,
 'B002039': 892,
 'B002041': 893,
 'B002042': 894,
 'B002043': 895,
 'B002044': 896,
 'B002045': 897,
 'B002046': 898,
 'B002049': 899,
 'B002050': 900,
 'B002051': 901,
 'B002052': 902,
 'B002053': 903,
 'B002054': 904,
 'B002055': 905,
 'B002056': 906,
 'B002057': 907,
 'B002058': 908,
 'B002060': 909,
 'B002061': 910,
 'B002062': 911,
 'B002063': 912,
 'B002065': 913,
 'B002066': 914,
 'B002067': 915,
 'B002068': 916,
 'B002071': 917,
 'B002072': 918,
 'B002073': 919,
 'B002074': 920,
 'B002075': 921,
 'B002076': 922,
 'B002077': 923,
 'B002079': 924,
 'B002080': 925,
 'B002082': 926,
 'B002083': 927,
 'B002084': 928,
 'B002086': 929,
 'B002091': 930,
 'B002092': 931,
 'B002093': 932,
 'B002094': 933,
 'B002095': 934,
 'B002096': 935,
 'B002098': 936,
 'B002102': 937,
 'B002103': 938,
 'B002104': 939,
 'B002105': 940,
 'B002107': 941,
 'B002108': 942,
 'B002109': 943,
 'B002110': 944,
 'B002114': 945,
 'B002115': 946,
 'B002116': 947,
 'B002117': 948,
 'B002121': 949,
 'B002123': 950,
 'B002125': 951,
 'B002126': 952,
 'B002127': 953,
 'B002128': 954,
 'B002129': 955,
 'B002130': 956,
 'B002132': 957,
 'B002133': 958,
 'B002134': 959,
 'B002135': 960,
 'B002139': 961,
 'B002140': 962,
 'B002141': 963,
 'B002144': 964,
 'B002146': 965,
 'B002147': 966,
 'B002148': 967,
 'B002149': 968,
 'B002150': 969,
 'B002151': 970,
 'B002152': 971,
 'B002153': 972,
 'B002163': 973,
 'B002164': 974,
 'B002165': 975,
 'B002169': 976,
 'B002170': 977,
 'B002172': 978,
 'B002173': 979,
 'B002174': 980,
 'B002176': 981,
 'B002177': 982,
 'B002179': 983,
 'B002180': 984,
 'B002181': 985,
 'B002182': 986,
 'B002183': 987,
 'B002184': 988,
 'B002185': 989,
 'B002188': 990,
 'B002226': 991,
 'B002232': 992,
 'B002234': 993,
 'B002235': 994,
 'B002236': 995,
 'B002238': 996,
 'B002239': 997,
 'B002244': 998,
 'B002249': 999,
 'B002256': 1000,
 ...}

## user

In [7]:
users = pd.read_csv('data/users/all_users.csv')
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 1798 entries, 0 to 1797
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  1798 non-null   int64
 1   Unnamed: 0    1798 non-null   int64
 2   ID Anggota    1798 non-null   int64
 3   prodi_id      1785 non-null   str
 4   jurusan       1785 non-null   str
 5   fakultas_id   1786 non-null   float64
 6   fakultas      1785 non-null   str
 7   jenjang       1785 non-null   str
 8   Nama Anggota  1798 non-null   str
 9   role          1798 non-null   str
 10  angkatan      1775 non-null   float64
 11  userId        1798 non-null   int64
dtypes: float64(2), int64(4), str(6)
memory usage: 306.8 KB

In [8]:
users['userId'] = users.index + 1
users.head(10)

,Unnamed: 0.1,Unnamed: 0,ID Anggota,prodi_id,jurusan,fakultas_id,fakultas,jenjang,Nama Anggota,role,angkatan,userId
0,0,0,196207282021211000,12.0,Manajemen,1.0,Fakultas Ekonomi dan Bisnis,S1,Bowo Santoso,lecturer,NaN,1
1,1,1,196211201991032000,65.0,Magister Ilmu Lingkungan,3.0,Fakultas Teknik dan Sains,S2,"Dr.Ir.Susilowati,Mt",lecturer,NaN,2
2,2,2,196509291992032000,13.0,Akuntansi,1.0,Fakultas Ekonomi dan Bisnis,S1,Dra Ec Sri Trisnaningsih Msi,lecturer,NaN,3
3,3,3,196701231993032000,13.0,Akuntansi,1.0,Fakultas Ekonomi dan Bisnis,S1,Dra Ec Tituk Diah Widayantie M Aks,lecturer,NaN,4
4,4,4,197708172021212000,53.0,Desain Interior,5.0,Fakultas Arsitektur dan Desain,S1,Dyan Agustin,lecturer,NaN,5
5,5,5,198511062019031000,52.0,Desain Komunikasi Visual,5.0,Fakultas Arsitektur dan Desain,S1,Aris Sutejo,lecturer,NaN,6
6,6,6,198706172025062000,11.0,Ekonomi Pembangunan,1.0,Fakultas Ekonomi dan Bisnis,S1,"Dr. Eunike Rose Mita Lukiani, M.Pd",lecturer,NaN,7
7,7,7,199010282024062000,37.0,Fisika,3.0,Fakultas Teknik dan Sains,S1,Nenni Mona Aruan,lecturer,NaN,8
8,8,8,199312042024061000,37.0,Fisika,3.0,Fakultas Teknik dan Sains,S1,Fajar Timur,lecturer,NaN,9
9,9,9,199509302024062000,24.0,Agribisnis,2.0,Fakultas Pertanian,S1,Yesi Mustika Ningsih,lecturer,NaN,10

In [9]:
id_to_users = dict(zip(users['userId'], users['ID Anggota']))
id_to_users[0] = ""
id_to_users

{1: 196207282021211000,
 2: 196211201991032000,
 3: 196509291992032000,
 4: 196701231993032000,
 5: 197708172021212000,
 6: 198511062019031000,
 7: 198706172025062000,
 8: 199010282024062000,
 9: 199312042024061000,
 10: 199509302024062000,
 11: 199901062024062000,
 12: 17041010008,
 13: 18011010001,
 14: 18011010018,
 15: 18025010010,
 16: 18033010059,
 17: 18041010032,
 18: 19011010107,
 19: 19012010076,
 20: 19012010248,
 21: 19013010276,
 22: 19024010150,
 23: 19025010017,
 24: 19025010021,
 25: 19025010150,
 26: 19031010119,
 27: 19032010094,
 28: 19041010041,
 29: 19041010204,
 30: 19043010024,
 31: 19043010076,
 32: 19043010135,
 33: 19043010156,
 34: 19043010194,
 35: 19081010020,
 36: 19082010024,
 37: 19900308019,
 38: 20011010001,
 39: 20011010002,
 40: 20011010006,
 41: 20011010010,
 42: 20011010034,
 43: 20011010038,
 44: 20011010047,
 45: 20011010057,
 46: 20011010059,
 47: 20011010066,
 48: 20011010067,
 49: 20011010069,
 50: 20011010088,
 51: 20011010089,
 52: 20011010100,
 53: 20011010110,
 54: 20011010112,
 55: 20011010146,
 56: 20011010161,
 57: 20012010019,
 58: 20012010032,
 59: 20012010035,
 60: 20012010039,
 61: 20012010049,
 62: 20012010058,
 63: 20012010069,
 64: 20012010072,
 65: 20012010122,
 66: 20012010218,
 67: 20012010229,
 68: 20012010364,
 69: 20013010001,
 70: 20013010010,
 71: 20013010022,
 72: 20013010028,
 73: 20013010030,
 74: 20013010036,
 75: 20013010046,
 76: 20013010048,
 77: 20013010051,
 78: 20013010062,
 79: 20013010064,
 80: 20013010088,
 81: 20013010100,
 82: 20013010111,
 83: 20013010133,
 84: 20013010135,
 85: 20013010144,
 86: 20013010145,
 87: 20013010148,
 88: 20013010152,
 89: 20013010162,
 90: 20013010185,
 91: 20013010192,
 92: 20013010201,
 93: 20013010206,
 94: 20013010211,
 95: 20013010214,
 96: 20013010219,
 97: 20013010224,
 98: 20013010225,
 99: 20013010227,
 100: 20013010229,
 101: 20013010242,
 102: 20013010250,
 103: 20013010253,
 104: 20013010258,
 105: 20013010263,
 106: 20013010266,
 107: 20013010282,
 108: 20013010283,
 109: 20024010006,
 110: 20024010023,
 111: 20024010026,
 112: 20024010032,
 113: 20024010036,
 114: 20024010037,
 115: 20024010039,
 116: 20024010040,
 117: 20024010043,
 118: 20024010048,
 119: 20024010052,
 120: 20024010066,
 121: 20024010077,
 122: 20024010085,
 123: 20024010087,
 124: 20024010102,
 125: 20024010109,
 126: 20024010115,
 127: 20024010136,
 128: 20024010139,
 129: 20024010140,
 130: 20024010143,
 131: 20024010148,
 132: 20024010149,
 133: 20024010156,
 134: 20024010161,
 135: 20025010009,
 136: 20025010039,
 137: 20025010134,
 138: 20025010150,
 139: 20025010176,
 140: 20031010019,
 141: 20031010032,
 142: 20031010036,
 143: 20031010089,
 144: 20031010121,
 145: 20031010124,
 146: 20032010057,
 147: 20033010035,
 148: 20033010068,
 149: 20033010080,
 150: 20033010087,
 151: 20034010002,
 152: 20034010039,
 153: 20034010072,
 154: 20035010043,
 155: 20035010047,
 156: 20041010001,
 157: 20041010007,
 158: 20041010029,
 159: 20041010036,
 160: 20041010042,
 161: 20041010056,
 162: 20041010065,
 163: 20041010066,
 164: 20041010088,
 165: 20041010091,
 166: 20041010108,
 167: 20041010121,
 168: 20041010122,
 169: 20041010130,
 170: 20041010141,
 171: 20041010169,
 172: 20041010198,
 173: 20041010206,
 174: 20041010225,
 175: 20041010244,
 176: 20042010052,
 177: 20042010053,
 178: 20042010059,
 179: 20042010122,
 180: 20042010181,
 181: 20042010260,
 182: 20043010051,
 183: 20043010068,
 184: 20043010084,
 185: 20043010085,
 186: 20043010097,
 187: 20043010107,
 188: 20043010127,
 189: 20043010132,
 190: 20043010134,
 191: 20043010156,
 192: 20043010158,
 193: 20043010180,
 194: 20043010181,
 195: 20043010197,
 196: 20043010234,
 197: 20044010053,
 198: 20045010038,
 199: 20045010053,
 200: 20045010072,
 201: 20052010021,
 202: 20052010070,
 203: 20052010106,
 204: 20052010118,
 205: 20071010026,
 206: 20071010052,
 207: 20071010066,
 208: 20071010071,
 209: 20071010080,
 210: 20071010085,
 211: 20071010089,
 212: 20071010090,
 213: 20071010106,
 214: 20071010118,
 215: 20071010137,
 216: 20071010142,
 217: 20071010153,
 218: 20071010184,
 219: 20071010220,
 220: 20071010224,
 221: 20071010303,
 222: 20081010235,
 223: 20082010009,
 224: 20082010010,
 225: 20082010016,
 226: 20082010022,
 227: 20082010031,
 228: 20082010033,
 229: 20082010037,
 230: 20082010126,
 231: 20082010131,
 232: 20082010139,
 233: 20082010181,
 234: 21011010012,
 235: 21011010021,
 236: 21011010038,
 237: 21011010043,
 238: 21011010045,
 239: 21011010046,
 240: 21011010049,
 241: 21011010052,
 242: 21011010054,
 243: 21011010055,
 244: 21011010057,
 245: 21011010064,
 246: 21011010069,
 247: 21011010091,
 248: 21011010094,
 249: 21011010105,
 250: 21011010107,
 251: 21011010109,
 252: 21011010122,
 253: 21011010129,
 254: 21011010144,
 255: 21011010161,
 256: 21011010169,
 257: 21011010172,
 258: 21011010196,
 259: 21011010221,
 260: 21011010223,
 261: 21011010228,
 262: 21011010230,
 263: 21012010007,
 264: 21012010025,
 265: 21012010032,
 266: 21012010058,
 267: 21012010068,
 268: 21012010180,
 269: 21012010195,
 270: 21012010196,
 271: 21012010211,
 272: 21012010217,
 273: 21012010231,
 274: 21012010240,
 275: 21012010244,
 276: 21012010300,
 277: 21012010430,
 278: 21012010436,
 279: 21013010004,
 280: 21013010008,
 281: 21013010010,
 282: 21013010041,
 283: 21013010064,
 284: 21013010089,
 285: 21013010098,
 286: 21013010104,
 287: 21013010123,
 288: 21013010127,
 289: 21013010137,
 290: 21013010141,
 291: 21013010171,
 292: 21013010211,
 293: 21013010220,
 294: 21013010228,
 295: 21013010234,
 296: 21013010264,
 297: 21013010280,
 298: 21013010350,
 299: 21013010353,
 300: 21013010363,
 301: 21024010011,
 302: 21024010028,
 303: 21024010030,
 304: 21024010038,
 305: 21024010072,
 306: 21024010076,
 307: 21024010178,
 308: 21024010222,
 309: 21025010051,
 310: 21025010076,
 311: 21025010100,
 312: 21025010177,
 313: 21031010026,
 314: 21031010030,
 315: 21031010053,
 316: 21031010119,
 317: 21031010131,
 318: 21031010194,
 319: 21031010224,
 320: 21031010240,
 321: 21031010265,
 322: 21032010065,
 323: 21032010106,
 324: 21032010107,
 325: 21032010179,
 326: 21033010075,
 327: 21033010076,
 328: 21034010059,
 329: 21035010005,
 330: 21041010012,
 331: 21041010020,
 332: 21041010024,
 333: 21041010029,
 334: 21041010038,
 335: 21041010046,
 336: 21041010066,
 337: 21041010092,
 338: 21041010110,
 339: 21041010111,
 340: 21041010116,
 341: 21041010117,
 342: 21041010120,
 343: 21041010145,
 344: 21041010174,
 345: 21041010204,
 346: 21041010205,
 347: 21042010077,
 348: 21042010089,
 349: 21042010107,
 350: 21042010169,
 351: 21042010173,
 352: 21043010034,
 353: 21043010055,
 354: 21043010065,
 355: 21043010074,
 356: 21043010077,
 357: 21043010082,
 358: 21043010083,
 359: 21043010089,
 360: 21043010106,
 361: 21043010110,
 362: 21043010111,
 363: 21043010143,
 364: 21043010145,
 365: 21043010185,
 366: 21043010196,
 367: 21043010202,
 368: 21043010205,
 369: 21043010206,
 370: 21043010223,
 371: 21043010225,
 372: 21043010227,
 373: 21043010232,
 374: 21043010297,
 375: 21043010298,
 376: 21044010070,
 377: 21044010084,
 378: 21045010043,
 379: 21045010064,
 380: 21051010019,
 381: 21051010025,
 382: 21051010058,
 383: 21051010090,
 384: 21052010003,
 385: 21052010006,
 386: 21052010009,
 387: 21052010029,
 388: 21052010032,
 389: 21052010083,
 390: 21052010110,
 391: 21071010009,
 392: 21071010021,
 393: 21071010084,
 394: 21071010099,
 395: 21071010102,
 396: 21071010113,
 397: 21071010118,
 398: 21071010119,
 399: 21071010124,
 400: 21071010125,
 401: 21071010128,
 402: 21071010132,
 403: 21071010138,
 404: 21071010144,
 405: 21071010163,
 406: 21071010167,
 407: 21071010169,
 408: 21071010176,
 409: 21071010191,
 410: 21071010213,
 411: 21071010217,
 412: 21071010227,
 413: 21071010241,
 414: 21071010253,
 415: 21071010271,
 416: 21071010281,
 417: 21081010109,
 418: 21081010207,
 419: 21082010053,
 420: 21082010069,
 421: 21082010214,
 422: 22011010015,
 423: 22011010024,
 424: 22011010030,
 425: 22011010036,
 426: 22011010043,
 427: 22011010044,
 428: 22011010045,
 429: 22011010047,
 430: 22011010049,
 431: 22011010054,
 432: 22011010056,
 433: 22011010060,
 434: 22011010075,
 435: 22011010077,
 436: 22011010078,
 437: 22011010094,
 438: 22011010102,
 439: 22011010105,
 440: 22011010106,
 441: 22011010107,
 442: 22011010110,
 443: 22011010111,
 444: 22011010130,
 445: 22011010134,
 446: 22011010135,
 447: 22011010137,
 448: 22011010139,
 449: 22011010140,
 450: 22011010143,
 451: 22011010147,
 452: 22011010150,
 453: 22011010154,
 454: 22011010159,
 455: 22011010160,
 456: 22011010175,
 457: 22011010180,
 458: 22011010183,
 459: 22011010209,
 460: 22011010210,
 461: 22011010212,
 462: 22011010220,
 463: 22011010221,
 464: 22011010222,
 465: 22011010228,
 466: 22011010229,
 467: 22011011231,
 468: 22012010001,
 469: 22012010009,
 470: 22012010010,
 471: 22012010018,
 472: 22012010025,
 473: 22012010026,
 474: 22012010031,
 475: 22012010080,
 476: 22012010114,
 477: 22012010138,
 478: 22012010146,
 479: 22012010154,
 480: 22012010174,
 481: 22012010190,
 482: 22012010194,
 483: 22012010195,
 484: 22012010199,
 485: 22012010203,
 486: 22012010208,
 487: 22012010225,
 488: 22012010246,
 489: 22012010250,
 490: 22012010267,
 491: 22012010272,
 492: 22012010295,
 493: 22012010305,
 494: 22012010313,
 495: 22012010324,
 496: 22012010442,
 497: 22012010469,
 498: 22013010001,
 499: 22013010042,
 500: 22013010043,
 501: 22013010073,
 502: 22013010086,
 503: 22013010088,
 504: 22013010093,
 505: 22013010106,
 506: 22013010108,
 507: 22013010109,
 508: 22013010123,
 509: 22013010126,
 510: 22013010140,
 511: 22013010150,
 512: 22013010168,
 513: 22013010169,
 514: 22013010174,
 515: 22013010176,
 516: 22013010183,
 517: 22013010184,
 518: 22013010190,
 519: 22013010192,
 520: 22013010197,
 521: 22013010200,
 522: 22013010217,
 523: 22013010221,
 524: 22013010224,
 525: 22013010238,
 526: 22013010247,
 527: 22013010250,
 528: 22013010263,
 529: 22013010270,
 530: 22013010294,
 531: 22013010298,
 532: 22013010299,
 533: 22013010300,
 534: 22013010308,
 535: 22013010313,
 536: 22013010317,
 537: 22013010331,
 538: 22013010357,
 539: 22014010020,
 540: 22014010047,
 541: 22024010101,
 542: 22024010135,
 543: 22024010140,
 544: 22024010153,
 545: 22024010159,
 546: 22024010196,
 547: 22031010006,
 548: 22031010022,
 549: 22031010038,
 550: 22031010099,
 551: 22031010104,
 552: 22031010134,
 553: 22031010148,
 554: 22031010161,
 555: 22031010165,
 556: 22031010183,
 557: 22032010023,
 558: 22032010136,
 559: 22032010141,
 560: 22032010167,
 561: 22032010190,
 562: 22033010121,
 563: 22034010006,
 564: 22034010016,
 565: 22034010021,
 566: 22034010033,
 567: 22034010044,
 568: 22034010077,
 569: 22034010106,
 570: 22034010113,
 571: 22034010114,
 572: 22035010013,
 573: 22037010001,
 574: 22037010004,
 575: 22037010005,
 576: 22037010018,
 577: 22041010008,
 578: 22041010038,
 579: 22041010045,
 580: 22041010057,
 581: 22041010065,
 582: 22041010076,
 583: 22041010079,
 584: 22041010086,
 585: 22041010087,
 586: 22041010098,
 587: 22041010106,
 588: 22041010116,
 589: 22041010117,
 590: 22041010123,
 591: 22041010124,
 592: 22041010129,
 593: 22041010140,
 594: 22041010143,
 595: 22041010149,
 596: 22041010155,
 597: 22041010160,
 598: 22041010162,
 599: 22041010170,
 600: 22041010181,
 601: 22041010184,
 602: 22041010185,
 603: 22041010193,
 604: 22041010198,
 605: 22041010204,
 606: 22041010205,
 607: 22041010226,
 608: 22041010227,
 609: 22041010233,
 610: 22041010235,
 611: 22041010237,
 612: 22041010240,
 613: 22041010243,
 614: 22041010264,
 615: 22041010307,
 616: 22041011312,
 617: 22042010009,
 618: 22042010044,
 619: 22042010054,
 620: 22042010071,
 621: 22042010081,
 622: 22042010083,
 623: 22042010105,
 624: 22042010115,
 625: 22042010123,
 626: 22042010133,
 627: 22042010150,
 628: 22042010153,
 629: 22042010158,
 630: 22042010159,
 631: 22042010160,
 632: 22042010163,
 633: 22042010167,
 634: 22042010175,
 635: 22042010233,
 636: 22042010277,
 637: 22042011343,
 638: 22043010022,
 639: 22043010049,
 640: 22043010052,
 641: 22043010060,
 642: 22043010091,
 643: 22043010108,
 644: 22043010130,
 645: 22043010131,
 646: 22043010228,
 647: 22043010272,
 648: 22044010021,
 649: 22044010107,
 650: 22044010191,
 651: 22051010001,
 652: 22051010011,
 653: 22051010080,
 654: 22051010084,
 655: 22051010092,
 656: 22051010123,
 657: 22052010054,
 658: 22052010067,
 659: 22061020030,
 660: 22071010063,
 661: 22071010081,
 662: 22071010104,
 663: 22071010116,
 664: 22071010126,
 665: 22071010139,
 666: 22071010187,
 667: 22071010216,
 668: 22071010219,
 669: 22071010251,
 670: 22071010277,
 671: 22071010305,
 672: 22071310360,
 673: 22081010136,
 674: 22082010001,
 675: 22082010011,
 676: 22082010095,
 677: 22082010145,
 678: 22082010179,
 679: 23011010004,
 680: 23011010006,
 681: 23011010011,
 682: 23011010013,
 683: 23011010028,
 684: 23011010031,
 685: 23011010033,
 686: 23011010036,
 687: 23011010051,
 688: 23011010053,
 689: 23011010054,
 690: 23011010084,
 691: 23011010085,
 692: 23011010086,
 693: 23011010087,
 694: 23011010089,
 695: 23011010097,
 696: 23011010099,
 697: 23011010103,
 698: 23011010106,
 699: 23011010120,
 700: 23011010122,
 701: 23011010123,
 702: 23011010158,
 703: 23011010160,
 704: 23011010168,
 705: 23011010169,
 706: 23011010170,
 707: 23011010171,
 708: 23011010175,
 709: 23011010177,
 710: 23011010181,
 711: 23011010186,
 712: 23011010188,
 713: 23011010189,
 714: 23011010191,
 715: 23011010192,
 716: 23011010195,
 717: 23011010196,
 718: 23011010199,
 719: 23012010012,
 720: 23012010020,
 721: 23012010025,
 722: 23012010034,
 723: 23012010069,
 724: 23012010076,
 725: 23012010079,
 726: 23012010086,
 727: 23012010095,
 728: 23012010098,
 729: 23012010101,
 730: 23012010105,
 731: 23012010125,
 732: 23012010132,
 733: 23012010138,
 734: 23012010157,
 735: 23012010158,
 736: 23012010165,
 737: 23012010174,
 738: 23012010177,
 739: 23012010179,
 740: 23012010183,
 741: 23012010184,
 742: 23012010189,
 743: 23012010200,
 744: 23012010202,
 745: 23012010205,
 746: 23012010207,
 747: 23012010210,
 748: 23012010215,
 749: 23012010219,
 750: 23012010221,
 751: 23012010224,
 752: 23012010227,
 753: 23012010228,
 754: 23012010233,
 755: 23012010266,
 756: 23012010270,
 757: 23012010293,
 758: 23012010294,
 759: 23012010296,
 760: 23012010305,
 761: 23012010306,
 762: 23012010312,
 763: 23012010321,
 764: 23012010345,
 765: 23012010346,
 766: 23012010350,
 767: 23012010358,
 768: 23012010363,
 769: 23012010401,
 770: 23012010425,
 771: 23012010449,
 772: 23012010463,
 773: 23012010467,
 774: 23012010481,
 775: 23013010008,
 776: 23013010011,
 777: 23013010026,
 778: 23013010045,
 779: 23013010046,
 780: 23013010048,
 781: 23013010063,
 782: 23013010065,
 783: 23013010068,
 784: 23013010072,
 785: 23013010080,
 786: 23013010087,
 787: 23013010100,
 788: 23013010102,
 789: 23013010104,
 790: 23013010105,
 791: 23013010112,
 792: 23013010114,
 793: 23013010118,
 794: 23013010119,
 795: 23013010124,
 796: 23013010130,
 797: 23013010133,
 798: 23013010134,
 799: 23013010136,
 800: 23013010140,
 801: 23013010143,
 802: 23013010144,
 803: 23013010145,
 804: 23013010154,
 805: 23013010157,
 806: 23013010159,
 807: 23013010172,
 808: 23013010178,
 809: 23013010180,
 810: 23013010201,
 811: 23013010202,
 812: 23013010220,
 813: 23013010225,
 814: 23013010226,
 815: 23013010229,
 816: 23013010244,
 817: 23013010276,
 818: 23013010283,
 819: 23013010285,
 820: 23013010286,
 821: 23013010316,
 822: 23013010322,
 823: 23013010323,
 824: 23013010327,
 825: 23013010328,
 826: 23013010334,
 827: 23013010338,
 828: 23013010339,
 829: 23014010027,
 830: 23024010027,
 831: 23024010029,
 832: 23024010030,
 833: 23024010067,
 834: 23024010073,
 835: 23024010101,
 836: 23024010111,
 837: 23024010128,
 838: 23024010130,
 839: 23024010152,
 840: 23024010153,
 841: 23024010162,
 842: 23024010166,
 843: 23024010195,
 844: 23025010143,
 845: 23025010146,
 846: 23025010147,
 847: 23025010148,
 848: 23025010155,
 849: 23031010004,
 850: 23031010009,
 851: 23031010011,
 852: 23031010017,
 853: 23031010018,
 854: 23031010030,
 855: 23031010034,
 856: 23031010056,
 857: 23031010061,
 858: 23031010070,
 859: 23031010106,
 860: 23031010115,
 861: 23031010131,
 862: 23031010134,
 863: 23031010149,
 864: 23031010156,
 865: 23031010169,
 866: 23031010201,
 867: 23031010213,
 868: 23032010146,
 869: 23032010161,
 870: 23032010194,
 871: 23032010198,
 872: 23032010204,
 873: 23032010229,
 874: 23033010008,
 875: 23033010038,
 876: 23033010040,
 877: 23033010048,
 878: 23033010050,
 879: 23033010080,
 880: 23034010021,
 881: 23034010067,
 882: 23034010089,
 883: 23034010140,
 884: 23035010066,
 885: 23035010093,
 886: 23036010002,
 887: 23041010003,
 888: 23041010021,
 889: 23041010022,
 890: 23041010023,
 891: 23041010050,
 892: 23041010061,
 893: 23041010096,
 894: 23041010103,
 895: 23041010138,
 896: 23041010139,
 897: 23041010144,
 898: 23041010162,
 899: 23041010170,
 900: 23041010173,
 901: 23041010174,
 902: 23041010180,
 903: 23041010184,
 904: 23041010195,
 905: 23041010202,
 906: 23041010233,
 907: 23041010235,
 908: 23041010241,
 909: 23041010244,
 910: 23041010249,
 911: 23041010254,
 912: 23041010256,
 913: 23041010260,
 914: 23041010263,
 915: 23042010001,
 916: 23042010002,
 917: 23042010018,
 918: 23042010022,
 919: 23042010028,
 920: 23042010029,
 921: 23042010031,
 922: 23042010033,
 923: 23042010044,
 924: 23042010056,
 925: 23042010070,
 926: 23042010088,
 927: 23042010097,
 928: 23042010098,
 929: 23042010112,
 930: 23042010116,
 931: 23042010119,
 932: 23042010120,
 933: 23042010143,
 934: 23042010145,
 935: 23042010149,
 936: 23042010160,
 937: 23042010161,
 938: 23042010166,
 939: 23042010167,
 940: 23042010169,
 941: 23042010175,
 942: 23042010178,
 943: 23042010180,
 944: 23042010183,
 945: 23042010185,
 946: 23042010187,
 947: 23042010196,
 948: 23042010201,
 949: 23042010240,
 950: 23042010275,
 951: 23042010278,
 952: 23043010017,
 953: 23043010019,
 954: 23043010023,
 955: 23043010040,
 956: 23043010082,
 957: 23043010111,
 958: 23043010125,
 959: 23043010128,
 960: 23043010129,
 961: 23043010132,
 962: 23043010137,
 963: 23043010138,
 964: 23043010146,
 965: 23043010154,
 966: 23043010157,
 967: 23043010188,
 968: 23043010201,
 969: 23043010308,
 970: 23043010317,
 971: 23044010004,
 972: 23044010013,
 973: 23044010051,
 974: 23044010056,
 975: 23044010073,
 976: 23044010075,
 977: 23044010098,
 978: 23044010133,
 979: 23045010006,
 980: 23045010018,
 981: 23045010028,
 982: 23045010041,
 983: 23045010043,
 984: 23045010047,
 985: 23045010056,
 986: 23045010059,
 987: 23045010062,
 988: 23045010063,
 989: 23045010078,
 990: 23045010080,
 991: 23046010002,
 992: 23046010003,
 993: 23046010011,
 994: 23046010020,
 995: 23046010021,
 996: 23047010008,
 997: 23047010018,
 998: 23051010020,
 999: 23051010061,
 1000: 23051010129,
 ...}

In [10]:
users_to_id = dict(zip(users['ID Anggota'], users['userId']))
users_to_id[''] = 0
users_to_id

{196207282021211000: 1,
 196211201991032000: 2,
 196509291992032000: 3,
 196701231993032000: 4,
 197708172021212000: 5,
 198511062019031000: 6,
 198706172025062000: 7,
 199010282024062000: 8,
 199312042024061000: 9,
 199509302024062000: 10,
 199901062024062000: 11,
 17041010008: 12,
 18011010001: 13,
 18011010018: 14,
 18025010010: 15,
 18033010059: 16,
 18041010032: 17,
 19011010107: 18,
 19012010076: 19,
 19012010248: 20,
 19013010276: 21,
 19024010150: 22,
 19025010017: 23,
 19025010021: 24,
 19025010150: 25,
 19031010119: 26,
 19032010094: 27,
 19041010041: 28,
 19041010204: 29,
 19043010024: 30,
 19043010076: 31,
 19043010135: 32,
 19043010156: 33,
 19043010194: 34,
 19081010020: 35,
 19082010024: 36,
 19900308019: 37,
 20011010001: 38,
 20011010002: 39,
 20011010006: 40,
 20011010010: 41,
 20011010034: 42,
 20011010038: 43,
 20011010047: 44,
 20011010057: 45,
 20011010059: 46,
 20011010066: 47,
 20011010067: 48,
 20011010069: 49,
 20011010088: 50,
 20011010089: 51,
 20011010100: 52,
 20011010110: 53,
 20011010112: 54,
 20011010146: 55,
 20011010161: 56,
 20012010019: 57,
 20012010032: 58,
 20012010035: 59,
 20012010039: 60,
 20012010049: 61,
 20012010058: 62,
 20012010069: 63,
 20012010072: 64,
 20012010122: 65,
 20012010218: 66,
 20012010229: 67,
 20012010364: 68,
 20013010001: 69,
 20013010010: 70,
 20013010022: 71,
 20013010028: 72,
 20013010030: 73,
 20013010036: 74,
 20013010046: 75,
 20013010048: 76,
 20013010051: 77,
 20013010062: 78,
 20013010064: 79,
 20013010088: 80,
 20013010100: 81,
 20013010111: 82,
 20013010133: 83,
 20013010135: 84,
 20013010144: 85,
 20013010145: 86,
 20013010148: 87,
 20013010152: 88,
 20013010162: 89,
 20013010185: 90,
 20013010192: 91,
 20013010201: 92,
 20013010206: 93,
 20013010211: 94,
 20013010214: 95,
 20013010219: 96,
 20013010224: 97,
 20013010225: 98,
 20013010227: 99,
 20013010229: 100,
 20013010242: 101,
 20013010250: 102,
 20013010253: 103,
 20013010258: 104,
 20013010263: 105,
 20013010266: 106,
 20013010282: 107,
 20013010283: 108,
 20024010006: 109,
 20024010023: 110,
 20024010026: 111,
 20024010032: 112,
 20024010036: 113,
 20024010037: 114,
 20024010039: 115,
 20024010040: 116,
 20024010043: 117,
 20024010048: 118,
 20024010052: 119,
 20024010066: 120,
 20024010077: 121,
 20024010085: 122,
 20024010087: 123,
 20024010102: 124,
 20024010109: 125,
 20024010115: 126,
 20024010136: 127,
 20024010139: 128,
 20024010140: 129,
 20024010143: 130,
 20024010148: 131,
 20024010149: 132,
 20024010156: 133,
 20024010161: 134,
 20025010009: 135,
 20025010039: 136,
 20025010134: 137,
 20025010150: 138,
 20025010176: 139,
 20031010019: 140,
 20031010032: 141,
 20031010036: 142,
 20031010089: 143,
 20031010121: 144,
 20031010124: 145,
 20032010057: 146,
 20033010035: 147,
 20033010068: 148,
 20033010080: 149,
 20033010087: 150,
 20034010002: 151,
 20034010039: 152,
 20034010072: 153,
 20035010043: 154,
 20035010047: 155,
 20041010001: 156,
 20041010007: 157,
 20041010029: 158,
 20041010036: 159,
 20041010042: 160,
 20041010056: 161,
 20041010065: 162,
 20041010066: 163,
 20041010088: 164,
 20041010091: 165,
 20041010108: 166,
 20041010121: 167,
 20041010122: 168,
 20041010130: 169,
 20041010141: 170,
 20041010169: 171,
 20041010198: 172,
 20041010206: 173,
 20041010225: 174,
 20041010244: 175,
 20042010052: 176,
 20042010053: 177,
 20042010059: 178,
 20042010122: 179,
 20042010181: 180,
 20042010260: 181,
 20043010051: 182,
 20043010068: 183,
 20043010084: 184,
 20043010085: 185,
 20043010097: 186,
 20043010107: 187,
 20043010127: 188,
 20043010132: 189,
 20043010134: 190,
 20043010156: 191,
 20043010158: 192,
 20043010180: 193,
 20043010181: 194,
 20043010197: 195,
 20043010234: 196,
 20044010053: 197,
 20045010038: 198,
 20045010053: 199,
 20045010072: 200,
 20052010021: 201,
 20052010070: 202,
 20052010106: 203,
 20052010118: 204,
 20071010026: 205,
 20071010052: 206,
 20071010066: 207,
 20071010071: 208,
 20071010080: 209,
 20071010085: 210,
 20071010089: 211,
 20071010090: 212,
 20071010106: 213,
 20071010118: 214,
 20071010137: 215,
 20071010142: 216,
 20071010153: 217,
 20071010184: 218,
 20071010220: 219,
 20071010224: 220,
 20071010303: 221,
 20081010235: 222,
 20082010009: 223,
 20082010010: 224,
 20082010016: 225,
 20082010022: 226,
 20082010031: 227,
 20082010033: 228,
 20082010037: 229,
 20082010126: 230,
 20082010131: 231,
 20082010139: 232,
 20082010181: 233,
 21011010012: 234,
 21011010021: 235,
 21011010038: 236,
 21011010043: 237,
 21011010045: 238,
 21011010046: 239,
 21011010049: 240,
 21011010052: 241,
 21011010054: 242,
 21011010055: 243,
 21011010057: 244,
 21011010064: 245,
 21011010069: 246,
 21011010091: 247,
 21011010094: 248,
 21011010105: 249,
 21011010107: 250,
 21011010109: 251,
 21011010122: 252,
 21011010129: 253,
 21011010144: 254,
 21011010161: 255,
 21011010169: 256,
 21011010172: 257,
 21011010196: 258,
 21011010221: 259,
 21011010223: 260,
 21011010228: 261,
 21011010230: 262,
 21012010007: 263,
 21012010025: 264,
 21012010032: 265,
 21012010058: 266,
 21012010068: 267,
 21012010180: 268,
 21012010195: 269,
 21012010196: 270,
 21012010211: 271,
 21012010217: 272,
 21012010231: 273,
 21012010240: 274,
 21012010244: 275,
 21012010300: 276,
 21012010430: 277,
 21012010436: 278,
 21013010004: 279,
 21013010008: 280,
 21013010010: 281,
 21013010041: 282,
 21013010064: 283,
 21013010089: 284,
 21013010098: 285,
 21013010104: 286,
 21013010123: 287,
 21013010127: 288,
 21013010137: 289,
 21013010141: 290,
 21013010171: 291,
 21013010211: 292,
 21013010220: 293,
 21013010228: 294,
 21013010234: 295,
 21013010264: 296,
 21013010280: 297,
 21013010350: 298,
 21013010353: 299,
 21013010363: 300,
 21024010011: 301,
 21024010028: 302,
 21024010030: 303,
 21024010038: 304,
 21024010072: 305,
 21024010076: 306,
 21024010178: 307,
 21024010222: 308,
 21025010051: 309,
 21025010076: 310,
 21025010100: 311,
 21025010177: 312,
 21031010026: 313,
 21031010030: 314,
 21031010053: 315,
 21031010119: 316,
 21031010131: 317,
 21031010194: 318,
 21031010224: 319,
 21031010240: 320,
 21031010265: 321,
 21032010065: 322,
 21032010106: 323,
 21032010107: 324,
 21032010179: 325,
 21033010075: 326,
 21033010076: 327,
 21034010059: 328,
 21035010005: 329,
 21041010012: 330,
 21041010020: 331,
 21041010024: 332,
 21041010029: 333,
 21041010038: 334,
 21041010046: 335,
 21041010066: 336,
 21041010092: 337,
 21041010110: 338,
 21041010111: 339,
 21041010116: 340,
 21041010117: 341,
 21041010120: 342,
 21041010145: 343,
 21041010174: 344,
 21041010204: 345,
 21041010205: 346,
 21042010077: 347,
 21042010089: 348,
 21042010107: 349,
 21042010169: 350,
 21042010173: 351,
 21043010034: 352,
 21043010055: 353,
 21043010065: 354,
 21043010074: 355,
 21043010077: 356,
 21043010082: 357,
 21043010083: 358,
 21043010089: 359,
 21043010106: 360,
 21043010110: 361,
 21043010111: 362,
 21043010143: 363,
 21043010145: 364,
 21043010185: 365,
 21043010196: 366,
 21043010202: 367,
 21043010205: 368,
 21043010206: 369,
 21043010223: 370,
 21043010225: 371,
 21043010227: 372,
 21043010232: 373,
 21043010297: 374,
 21043010298: 375,
 21044010070: 376,
 21044010084: 377,
 21045010043: 378,
 21045010064: 379,
 21051010019: 380,
 21051010025: 381,
 21051010058: 382,
 21051010090: 383,
 21052010003: 384,
 21052010006: 385,
 21052010009: 386,
 21052010029: 387,
 21052010032: 388,
 21052010083: 389,
 21052010110: 390,
 21071010009: 391,
 21071010021: 392,
 21071010084: 393,
 21071010099: 394,
 21071010102: 395,
 21071010113: 396,
 21071010118: 397,
 21071010119: 398,
 21071010124: 399,
 21071010125: 400,
 21071010128: 401,
 21071010132: 402,
 21071010138: 403,
 21071010144: 404,
 21071010163: 405,
 21071010167: 406,
 21071010169: 407,
 21071010176: 408,
 21071010191: 409,
 21071010213: 410,
 21071010217: 411,
 21071010227: 412,
 21071010241: 413,
 21071010253: 414,
 21071010271: 415,
 21071010281: 416,
 21081010109: 417,
 21081010207: 418,
 21082010053: 419,
 21082010069: 420,
 21082010214: 421,
 22011010015: 422,
 22011010024: 423,
 22011010030: 424,
 22011010036: 425,
 22011010043: 426,
 22011010044: 427,
 22011010045: 428,
 22011010047: 429,
 22011010049: 430,
 22011010054: 431,
 22011010056: 432,
 22011010060: 433,
 22011010075: 434,
 22011010077: 435,
 22011010078: 436,
 22011010094: 437,
 22011010102: 438,
 22011010105: 439,
 22011010106: 440,
 22011010107: 441,
 22011010110: 442,
 22011010111: 443,
 22011010130: 444,
 22011010134: 445,
 22011010135: 446,
 22011010137: 447,
 22011010139: 448,
 22011010140: 449,
 22011010143: 450,
 22011010147: 451,
 22011010150: 452,
 22011010154: 453,
 22011010159: 454,
 22011010160: 455,
 22011010175: 456,
 22011010180: 457,
 22011010183: 458,
 22011010209: 459,
 22011010210: 460,
 22011010212: 461,
 22011010220: 462,
 22011010221: 463,
 22011010222: 464,
 22011010228: 465,
 22011010229: 466,
 22011011231: 467,
 22012010001: 468,
 22012010009: 469,
 22012010010: 470,
 22012010018: 471,
 22012010025: 472,
 22012010026: 473,
 22012010031: 474,
 22012010080: 475,
 22012010114: 476,
 22012010138: 477,
 22012010146: 478,
 22012010154: 479,
 22012010174: 480,
 22012010190: 481,
 22012010194: 482,
 22012010195: 483,
 22012010199: 484,
 22012010203: 485,
 22012010208: 486,
 22012010225: 487,
 22012010246: 488,
 22012010250: 489,
 22012010267: 490,
 22012010272: 491,
 22012010295: 492,
 22012010305: 493,
 22012010313: 494,
 22012010324: 495,
 22012010442: 496,
 22012010469: 497,
 22013010001: 498,
 22013010042: 499,
 22013010043: 500,
 22013010073: 501,
 22013010086: 502,
 22013010088: 503,
 22013010093: 504,
 22013010106: 505,
 22013010108: 506,
 22013010109: 507,
 22013010123: 508,
 22013010126: 509,
 22013010140: 510,
 22013010150: 511,
 22013010168: 512,
 22013010169: 513,
 22013010174: 514,
 22013010176: 515,
 22013010183: 516,
 22013010184: 517,
 22013010190: 518,
 22013010192: 519,
 22013010197: 520,
 22013010200: 521,
 22013010217: 522,
 22013010221: 523,
 22013010224: 524,
 22013010238: 525,
 22013010247: 526,
 22013010250: 527,
 22013010263: 528,
 22013010270: 529,
 22013010294: 530,
 22013010298: 531,
 22013010299: 532,
 22013010300: 533,
 22013010308: 534,
 22013010313: 535,
 22013010317: 536,
 22013010331: 537,
 22013010357: 538,
 22014010020: 539,
 22014010047: 540,
 22024010101: 541,
 22024010135: 542,
 22024010140: 543,
 22024010153: 544,
 22024010159: 545,
 22024010196: 546,
 22031010006: 547,
 22031010022: 548,
 22031010038: 549,
 22031010099: 550,
 22031010104: 551,
 22031010134: 552,
 22031010148: 553,
 22031010161: 554,
 22031010165: 555,
 22031010183: 556,
 22032010023: 557,
 22032010136: 558,
 22032010141: 559,
 22032010167: 560,
 22032010190: 561,
 22033010121: 562,
 22034010006: 563,
 22034010016: 564,
 22034010021: 565,
 22034010033: 566,
 22034010044: 567,
 22034010077: 568,
 22034010106: 569,
 22034010113: 570,
 22034010114: 571,
 22035010013: 572,
 22037010001: 573,
 22037010004: 574,
 22037010005: 575,
 22037010018: 576,
 22041010008: 577,
 22041010038: 578,
 22041010045: 579,
 22041010057: 580,
 22041010065: 581,
 22041010076: 582,
 22041010079: 583,
 22041010086: 584,
 22041010087: 585,
 22041010098: 586,
 22041010106: 587,
 22041010116: 588,
 22041010117: 589,
 22041010123: 590,
 22041010124: 591,
 22041010129: 592,
 22041010140: 593,
 22041010143: 594,
 22041010149: 595,
 22041010155: 596,
 22041010160: 597,
 22041010162: 598,
 22041010170: 599,
 22041010181: 600,
 22041010184: 601,
 22041010185: 602,
 22041010193: 603,
 22041010198: 604,
 22041010204: 605,
 22041010205: 606,
 22041010226: 607,
 22041010227: 608,
 22041010233: 609,
 22041010235: 610,
 22041010237: 611,
 22041010240: 612,
 22041010243: 613,
 22041010264: 614,
 22041010307: 615,
 22041011312: 616,
 22042010009: 617,
 22042010044: 618,
 22042010054: 619,
 22042010071: 620,
 22042010081: 621,
 22042010083: 622,
 22042010105: 623,
 22042010115: 624,
 22042010123: 625,
 22042010133: 626,
 22042010150: 627,
 22042010153: 628,
 22042010158: 629,
 22042010159: 630,
 22042010160: 631,
 22042010163: 632,
 22042010167: 633,
 22042010175: 634,
 22042010233: 635,
 22042010277: 636,
 22042011343: 637,
 22043010022: 638,
 22043010049: 639,
 22043010052: 640,
 22043010060: 641,
 22043010091: 642,
 22043010108: 643,
 22043010130: 644,
 22043010131: 645,
 22043010228: 646,
 22043010272: 647,
 22044010021: 648,
 22044010107: 649,
 22044010191: 650,
 22051010001: 651,
 22051010011: 652,
 22051010080: 653,
 22051010084: 654,
 22051010092: 655,
 22051010123: 656,
 22052010054: 657,
 22052010067: 658,
 22061020030: 659,
 22071010063: 660,
 22071010081: 661,
 22071010104: 662,
 22071010116: 663,
 22071010126: 664,
 22071010139: 665,
 22071010187: 666,
 22071010216: 667,
 22071010219: 668,
 22071010251: 669,
 22071010277: 670,
 22071010305: 671,
 22071310360: 672,
 22081010136: 673,
 22082010001: 674,
 22082010011: 675,
 22082010095: 676,
 22082010145: 677,
 22082010179: 678,
 23011010004: 679,
 23011010006: 680,
 23011010011: 681,
 23011010013: 682,
 23011010028: 683,
 23011010031: 684,
 23011010033: 685,
 23011010036: 686,
 23011010051: 687,
 23011010053: 688,
 23011010054: 689,
 23011010084: 690,
 23011010085: 691,
 23011010086: 692,
 23011010087: 693,
 23011010089: 694,
 23011010097: 695,
 23011010099: 696,
 23011010103: 697,
 23011010106: 698,
 23011010120: 699,
 23011010122: 700,
 23011010123: 701,
 23011010158: 702,
 23011010160: 703,
 23011010168: 704,
 23011010169: 705,
 23011010170: 706,
 23011010171: 707,
 23011010175: 708,
 23011010177: 709,
 23011010181: 710,
 23011010186: 711,
 23011010188: 712,
 23011010189: 713,
 23011010191: 714,
 23011010192: 715,
 23011010195: 716,
 23011010196: 717,
 23011010199: 718,
 23012010012: 719,
 23012010020: 720,
 23012010025: 721,
 23012010034: 722,
 23012010069: 723,
 23012010076: 724,
 23012010079: 725,
 23012010086: 726,
 23012010095: 727,
 23012010098: 728,
 23012010101: 729,
 23012010105: 730,
 23012010125: 731,
 23012010132: 732,
 23012010138: 733,
 23012010157: 734,
 23012010158: 735,
 23012010165: 736,
 23012010174: 737,
 23012010177: 738,
 23012010179: 739,
 23012010183: 740,
 23012010184: 741,
 23012010189: 742,
 23012010200: 743,
 23012010202: 744,
 23012010205: 745,
 23012010207: 746,
 23012010210: 747,
 23012010215: 748,
 23012010219: 749,
 23012010221: 750,
 23012010224: 751,
 23012010227: 752,
 23012010228: 753,
 23012010233: 754,
 23012010266: 755,
 23012010270: 756,
 23012010293: 757,
 23012010294: 758,
 23012010296: 759,
 23012010305: 760,
 23012010306: 761,
 23012010312: 762,
 23012010321: 763,
 23012010345: 764,
 23012010346: 765,
 23012010350: 766,
 23012010358: 767,
 23012010363: 768,
 23012010401: 769,
 23012010425: 770,
 23012010449: 771,
 23012010463: 772,
 23012010467: 773,
 23012010481: 774,
 23013010008: 775,
 23013010011: 776,
 23013010026: 777,
 23013010045: 778,
 23013010046: 779,
 23013010048: 780,
 23013010063: 781,
 23013010065: 782,
 23013010068: 783,
 23013010072: 784,
 23013010080: 785,
 23013010087: 786,
 23013010100: 787,
 23013010102: 788,
 23013010104: 789,
 23013010105: 790,
 23013010112: 791,
 23013010114: 792,
 23013010118: 793,
 23013010119: 794,
 23013010124: 795,
 23013010130: 796,
 23013010133: 797,
 23013010134: 798,
 23013010136: 799,
 23013010140: 800,
 23013010143: 801,
 23013010144: 802,
 23013010145: 803,
 23013010154: 804,
 23013010157: 805,
 23013010159: 806,
 23013010172: 807,
 23013010178: 808,
 23013010180: 809,
 23013010201: 810,
 23013010202: 811,
 23013010220: 812,
 23013010225: 813,
 23013010226: 814,
 23013010229: 815,
 23013010244: 816,
 23013010276: 817,
 23013010283: 818,
 23013010285: 819,
 23013010286: 820,
 23013010316: 821,
 23013010322: 822,
 23013010323: 823,
 23013010327: 824,
 23013010328: 825,
 23013010334: 826,
 23013010338: 827,
 23013010339: 828,
 23014010027: 829,
 23024010027: 830,
 23024010029: 831,
 23024010030: 832,
 23024010067: 833,
 23024010073: 834,
 23024010101: 835,
 23024010111: 836,
 23024010128: 837,
 23024010130: 838,
 23024010152: 839,
 23024010153: 840,
 23024010162: 841,
 23024010166: 842,
 23024010195: 843,
 23025010143: 844,
 23025010146: 845,
 23025010147: 846,
 23025010148: 847,
 23025010155: 848,
 23031010004: 849,
 23031010009: 850,
 23031010011: 851,
 23031010017: 852,
 23031010018: 853,
 23031010030: 854,
 23031010034: 855,
 23031010056: 856,
 23031010061: 857,
 23031010070: 858,
 23031010106: 859,
 23031010115: 860,
 23031010131: 861,
 23031010134: 862,
 23031010149: 863,
 23031010156: 864,
 23031010169: 865,
 23031010201: 866,
 23031010213: 867,
 23032010146: 868,
 23032010161: 869,
 23032010194: 870,
 23032010198: 871,
 23032010204: 872,
 23032010229: 873,
 23033010008: 874,
 23033010038: 875,
 23033010040: 876,
 23033010048: 877,
 23033010050: 878,
 23033010080: 879,
 23034010021: 880,
 23034010067: 881,
 23034010089: 882,
 23034010140: 883,
 23035010066: 884,
 23035010093: 885,
 23036010002: 886,
 23041010003: 887,
 23041010021: 888,
 23041010022: 889,
 23041010023: 890,
 23041010050: 891,
 23041010061: 892,
 23041010096: 893,
 23041010103: 894,
 23041010138: 895,
 23041010139: 896,
 23041010144: 897,
 23041010162: 898,
 23041010170: 899,
 23041010173: 900,
 23041010174: 901,
 23041010180: 902,
 23041010184: 903,
 23041010195: 904,
 23041010202: 905,
 23041010233: 906,
 23041010235: 907,
 23041010241: 908,
 23041010244: 909,
 23041010249: 910,
 23041010254: 911,
 23041010256: 912,
 23041010260: 913,
 23041010263: 914,
 23042010001: 915,
 23042010002: 916,
 23042010018: 917,
 23042010022: 918,
 23042010028: 919,
 23042010029: 920,
 23042010031: 921,
 23042010033: 922,
 23042010044: 923,
 23042010056: 924,
 23042010070: 925,
 23042010088: 926,
 23042010097: 927,
 23042010098: 928,
 23042010112: 929,
 23042010116: 930,
 23042010119: 931,
 23042010120: 932,
 23042010143: 933,
 23042010145: 934,
 23042010149: 935,
 23042010160: 936,
 23042010161: 937,
 23042010166: 938,
 23042010167: 939,
 23042010169: 940,
 23042010175: 941,
 23042010178: 942,
 23042010180: 943,
 23042010183: 944,
 23042010185: 945,
 23042010187: 946,
 23042010196: 947,
 23042010201: 948,
 23042010240: 949,
 23042010275: 950,
 23042010278: 951,
 23043010017: 952,
 23043010019: 953,
 23043010023: 954,
 23043010040: 955,
 23043010082: 956,
 23043010111: 957,
 23043010125: 958,
 23043010128: 959,
 23043010129: 960,
 23043010132: 961,
 23043010137: 962,
 23043010138: 963,
 23043010146: 964,
 23043010154: 965,
 23043010157: 966,
 23043010188: 967,
 23043010201: 968,
 23043010308: 969,
 23043010317: 970,
 23044010004: 971,
 23044010013: 972,
 23044010051: 973,
 23044010056: 974,
 23044010073: 975,
 23044010075: 976,
 23044010098: 977,
 23044010133: 978,
 23045010006: 979,
 23045010018: 980,
 23045010028: 981,
 23045010041: 982,
 23045010043: 983,
 23045010047: 984,
 23045010056: 985,
 23045010059: 986,
 23045010062: 987,
 23045010063: 988,
 23045010078: 989,
 23045010080: 990,
 23046010002: 991,
 23046010003: 992,
 23046010011: 993,
 23046010020: 994,
 23046010021: 995,
 23047010008: 996,
 23047010018: 997,
 23051010020: 998,
 23051010061: 999,
 23051010129: 1000,
 ...}

In [11]:
users[users['ID Anggota'] == 22082010145]

,Unnamed: 0.1,Unnamed: 0,ID Anggota,prodi_id,jurusan,fakultas_id,fakultas,jenjang,Nama Anggota,role,angkatan,userId
676,676,676,22082010145,Sistem Informasi,8.0,82.0,Fakultas Ilmu Komputer,S1,Mafda Khoirotul Fatha,student,2022.0,677

In [12]:
users.to_csv('data/users/all_users.csv')

# trans

In [13]:
trans_pd = pd.read_csv('data/processed/transactions_enriched.csv', low_memory=False, delimiter=';')
trans_pd.info()

<class 'pandas.DataFrame'>
RangeIndex: 5372 entries, 0 to 5371
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID Anggota          5372 non-null   int64
 1   Nama Anggota        5372 non-null   str
 2   Kode Eksemplar      5372 non-null   int64
 3   Judul               5372 non-null   str
 4   Tanggal Pinjam      5372 non-null   str
 5   tahun_pinjam        5372 non-null   int64
 6   bulan_pinjam        5372 non-null   int64
 7   bulan_tahun_pinjam  5372 non-null   str
 8   book_id             5372 non-null   str
dtypes: int64(4), str(5)
memory usage: 830.7 KB

In [14]:
trans_pd.sample(5)

,ID Anggota,Nama Anggota,Kode Eksemplar,Judul,Tanggal Pinjam,tahun_pinjam,bulan_pinjam,bulan_tahun_pinjam,book_id
1712,18011010001,Winarti,91115303,Pengelolaan Keuangan Pada Satuan Kerja Perangk...,2024-05-14,2024,5,2024-05,B018260
806,21011010021,ALYA ROHANI,90888602,Manajemen Perbankan : Teori dan Aplikasi,2023-12-18,2023,12,2023-12,B023412
314,23011010087,Anggita Eka Prameswari,90922503,Etika bisnis : konsep dan kasus,2023-10-17,2023,10,2023-10,B024880
1028,197708172021212000,Dyan Agustin,90840703,Arsitektur dan perilaku manusia,2024-01-12,2024,1,2024-01,B024891
1810,22012010025,LINTANG KINANTHI KUSUMAWARDANI,91101605,"Perilaku dan manajemen organisasi , Jilid 2",2024-05-31,2024,5,2024-05,B017987

In [15]:
trans_pd['userId'] = trans_pd['ID Anggota'].map(users_to_id)
trans_pd['bookId'] = trans_pd['book_id'].map(books_to_id)

trans_pd.sample(5)

,ID Anggota,Nama Anggota,Kode Eksemplar,Judul,Tanggal Pinjam,tahun_pinjam,bulan_pinjam,bulan_tahun_pinjam,book_id,userId,bookId
1156,21035010005,MUHAMMAD AINUN NASRUL MAJID,91075001,Modul ajar teknik gempa,2024-02-15,2024,2,2024-02,B018446,329,12263
1130,22013010238,TALITHA RAISSA ASMAWATI,91081803,Sistem informasi manajemen,2024-02-07,2024,2,2024-02,B019904,525,12695
1088,20013010224,Gisella Chantika Neyza,91297408,"Partial least squares : konsep, teknik dan apl...",2024-01-30,2024,1,2024-01,B024742,97,13923
1171,23032010161,Pinto Legowo Abhima Putra,90313603,HEAT TRANSFER,2024-02-16,2024,2,2024-02,B000231,869,79
939,22011010159,ANGGIE WAHYUWARDANI,923021705,Mikroekonomi : Teori pengantar,2023-12-20,2023,12,2023-12,B020279,454,12802

In [16]:
trans_pd['timestamp'] = pd.to_datetime(trans_pd['Tanggal Pinjam'])
trans_pd.info()

<class 'pandas.DataFrame'>
RangeIndex: 5372 entries, 0 to 5371
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID Anggota          5372 non-null   int64
 1   Nama Anggota        5372 non-null   str
 2   Kode Eksemplar      5372 non-null   int64
 3   Judul               5372 non-null   str
 4   Tanggal Pinjam      5372 non-null   str
 5   tahun_pinjam        5372 non-null   int64
 6   bulan_pinjam        5372 non-null   int64
 7   bulan_tahun_pinjam  5372 non-null   str
 8   book_id             5372 non-null   str
 9   userId              5372 non-null   int64
 10  bookId              5372 non-null   int64
 11  timestamp           5372 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(6), str(5)
memory usage: 956.6 KB

In [17]:
trans_pd['timestamp'].sample()

1746   2024-05-17
Name: timestamp, dtype: datetime64[us]

In [18]:
trans_pd.isna().sum()

ID Anggota            0
Nama Anggota          0
Kode Eksemplar        0
Judul                 0
Tanggal Pinjam        0
tahun_pinjam          0
bulan_pinjam          0
bulan_tahun_pinjam    0
book_id               0
userId                0
bookId                0
timestamp             0
dtype: int64

In [19]:
trans = trans_pd[['userId', 'bookId', 'timestamp']]

# Sequence

In [20]:
def build_sequence(transaction_data):
    sequences = defaultdict(list)
    for userId, bookId, timestamp in trans.values:
            sequences[userId].append(
                {
                    "bookId": bookId,
                    "timestamp": timestamp,
                }
            )
    # Sort sequences by timestamp for every user.
    for user_id, context in sequences.items():
        context.sort(key=lambda x: x["timestamp"])
        sequences[user_id] = context

    return sequences

In [21]:
sequences = build_sequence(trans)

## Negative Sequence

In [22]:
books_count = books.shape[0]
books_count

14502

In [23]:
def build_negative_seq(sequences):
    examples = {
        "sequence": [],
        "negative_sequence": [],
    }

    for userId in sequences:
        sequence = [int(d["bookId"]) for d in sequences[userId]]

        # Get negative sequence.
        def random_negative_item_id(low, high, positive_lst):
            sampled = np.random.randint(low=low, high=high)
            while sampled in positive_lst:
                sampled = np.random.randint(low=low, high=high)
            return sampled

        negative_sequence = [
            random_negative_item_id(1, books_count + 1, sequence)
            for _ in range(len(sequence))
        ]

        examples["sequence"].append(np.array(sequence))
        examples["negative_sequence"].append(np.array(negative_sequence))

    examples["sequence"] = tf.ragged.constant(examples["sequence"])
    examples["negative_sequence"] = tf.ragged.constant(examples["negative_sequence"])

    return examples

In [24]:
examples = build_negative_seq(sequences)

## Split Data Train Val Test

In [25]:
from collections import defaultdict

def data_split(sequences):
    user_train, user_valid, user_test = {}, {}, {}
    itemnum = 0

    for user, seq in sequences.items():
        # sort by timestamp
        seq_sorted = sorted(seq, key=lambda x: x["timestamp"])
        book_ids = [int(x["bookId"]) for x in seq_sorted]
        itemnum = max(itemnum, max(book_ids))

        n = len(book_ids)

        if n < 2:
            # Panjang 1: Tidak bisa diuji
            user_train[user] = book_ids
            user_valid[user] = []
            user_test[user] = []
        elif n == 2:
            # Panjang 2:
            user_train[user] = book_ids
            user_valid[user] = []
            user_test[user] = []
        elif n == 3:
            # Panjang 3:
            user_train[user] = book_ids[:-1] 
            user_valid[user] = []
            user_test[user] = book_ids
        else:
            # Panjang > 3
            user_train[user] = book_ids[:-2]
            user_valid[user] = book_ids[:-1]
            user_test[user] = book_ids

    return user_train, user_valid, user_test, itemnum

In [26]:
train, valid, test, itemnum = data_split(sequences)

# Padding

In [27]:
def build_tf_dataset(user_dict, itemnum):
    sequences = []
    negative_sequences = []

    for u, seq in user_dict.items():
        if not seq: continue
        # Ensure sequence is a NumPy array for consistency
        seq_np = np.array(seq, dtype=np.int32)
        # Generate negative samples for the sequence length
        negative_seq_np = np.random.randint(1, itemnum + 1, size=len(seq_np))

        sequences.append(seq_np)
        negative_sequences.append(negative_seq_np)

    # Convert lists of NumPy arrays (sequences) into Ragged Tensors
    ragged_examples = {
        "sequence": tf.ragged.constant(sequences, dtype=tf.int32),
        "negative_sequence": tf.ragged.constant(negative_sequences, dtype=tf.int32),
    }

    # Create the dataset from the ragged tensors, and then batch it
    ds = tf.data.Dataset.from_tensor_slices(ragged_examples)

    return ds

In [28]:
def _preprocess(example, train=True):
    seq = example["sequence"]
    neg_seq = example["negative_sequence"]
    batch_size = tf.shape(seq)[0]

    if train:
        # Example seq: [A, B, C] -> input: [A, B], target: [B, C]
        inputs = seq[..., :-1]
        targets = seq[..., 1:]
        neg_targets = neg_seq[..., 1:]

        # Truncate to MAX_CONTEXT_LENGTH
        inputs = inputs[..., -MAX_CONTEXT_LENGTH:]
        targets = targets[..., -MAX_CONTEXT_LENGTH:]
        neg_targets = neg_targets[..., -MAX_CONTEXT_LENGTH:]

        # Pad dynamically
        inputs_padded = inputs.to_tensor(shape=[batch_size, MAX_CONTEXT_LENGTH], default_value=PAD_ITEM_ID)
        targets_padded = targets.to_tensor(shape=[batch_size, MAX_CONTEXT_LENGTH], default_value=PAD_ITEM_ID)
        neg_targets_padded = neg_targets.to_tensor(shape=[batch_size, MAX_CONTEXT_LENGTH], default_value=PAD_ITEM_ID)

        # Sample weight: 1.0 for real target items, 0.0 for padding
        sample_weight = tf.cast(targets_padded != PAD_ITEM_ID, dtype="float32")

        return (
            {
                "item_ids": inputs_padded,
                "padding_mask": inputs_padded != PAD_ITEM_ID,
            },
            {
                "positive_sequence": targets_padded,
                "negative_sequence": neg_targets_padded,
            },
            sample_weight
        )
    else:
        # For testing: Context is everything EXCEPT the last item. Target IS the last item.
        # Example seq: [A, B, C] -> context: [A, B], target: [C]
        context = seq[..., :-1]
        target = seq[..., -1:]

        # Truncate context
        context = context[..., -MAX_CONTEXT_LENGTH:]
        
        context_padded = context.to_tensor(shape=[batch_size, MAX_CONTEXT_LENGTH], default_value=PAD_ITEM_ID)
        
        # Flatten target into a 1D tensor [batch_size]
        target_flat = tf.reshape(target.to_tensor(), [batch_size])

        return (
            {
                "item_ids": context_padded,
                "padding_mask": context_padded != PAD_ITEM_ID,
            },
            {
                "positive_sequence": target_flat,
            }
        )

In [29]:
def preprocess_train(examples):
    return _preprocess(examples, train=True)
def preprocess_val(examples):
    return _preprocess(examples, train=False)
def preprocess_test(examples):
    return _preprocess(examples, train=False)

In [30]:
user_train, user_valid, user_test, itemnum = data_split(sequences)

In [31]:
print(f"Jumlah user di Train set: {sum(1 for v in user_train.values() if v)}")
print(f"Jumlah user di Valid set: {sum(1 for v in user_valid.values() if v)}")
print(f"Jumlah user di Test set:  {sum(1 for v in user_test.values() if v)}")

Jumlah user di Train set: 1798
Jumlah user di Valid set: 396
Jumlah user di Test set:  633

In [32]:
train_ds = build_tf_dataset(user_train, itemnum).batch(BATCH_SIZE).map(preprocess_train)
val_ds = build_tf_dataset(user_valid, itemnum).batch(BATCH_SIZE).map(preprocess_val)
test_ds = build_tf_dataset(user_test, itemnum).batch(BATCH_SIZE).map(preprocess_test)

# cold warm set

## users

In [33]:
import math

# sequence_lengths = [len(seq) for seq in sequences.values()]
# print(f"max seq length: {max(sequence_lengths)}")
# percentile_20 = np.percentile(sequence_lengths, 20)
# user_threshold = math.ceil(percentile_20)

testable_seq_lengths = [len(seq) for seq in sequences.values() if len(seq) >= 2]
user_threshold = np.percentile(testable_seq_lengths, 20)

print(f"Ambang Batas (Threshold) Pengguna: {user_threshold} interaksi")

Ambang Batas (Threshold) Pengguna: 2.0 interaksi

In [34]:
cold_users = set()
warm_users = set()

for user, seq in sequences.items():
    if len(seq) <= user_threshold:
        cold_users.add(user)
    else:
        warm_users.add(user)

print(f"Total Cold Users: {len(cold_users)}")
print(f"Total Warm Users: {len(warm_users)}")

Total Cold Users: 1165
Total Warm Users: 633

## items

In [35]:
warm_items = set()

# Item yang muncul pada train set adalah warm-item
for user, seq in user_train.items():
    warm_items.update(seq)

# Mencari total seluruh item unik yang ada (berdasarkan dictionary sequence awal)
all_items_in_data = set()
for user, seq in sequences.items():
    for interaksi in seq:
        all_items_in_data.add(int(interaksi["bookId"]))

# Item yang ada di dataset tapi TIDAK ada di train set adalah cold-item
cold_items = all_items_in_data - warm_items

print(f"Total Warm Items: {len(warm_items)}")
print(f"Total Cold Items: {len(cold_items)}")

Total Warm Items: 1747
Total Cold Items: 213

In [37]:
books['type'] = 'cold'
books.loc[books['bookId'].isin(warm_items), 'type'] = 'warm'
books.to_csv('data/processed/books_enriched_with_type.csv', index=False, sep=';')

In [ ]:
books['type'].value_counts()

type
cold    12755
warm     1747
Name: count, dtype: int64

In [ ]:
books[books['judul'] == ]